In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
df1_path = "train500.csv"
#df2_path = "test.csv"

In [3]:
df = pd.read_csv(df1_path)
print(df.shape)
df.head()

(499, 12)

,user_id,session_id,timestamp,step,action_type,reference,platform,city,device,current_filters,impressions,prices
0,00RL8Z82B2Z1,aff3928535f48,1541037460,1,search for poi,Newtown,AU,"Sydney, Australia",mobile,NaN,NaN,NaN
1,00RL8Z82B2Z1,aff3928535f48,1541037522,2,interaction item image,666856,AU,"Sydney, Australia",mobile,NaN,NaN,NaN
2,00RL8Z82B2Z1,aff3928535f48,1541037522,3,interaction item image,666856,AU,"Sydney, Australia",mobile,NaN,NaN,NaN
3,00RL8Z82B2Z1,aff3928535f48,1541037532,4,interaction item image,666856,AU,"Sydney, Australia",mobile,NaN,NaN,NaN
4,00RL8Z82B2Z1,aff3928535f48,1541037532,5,interaction item image,109038,AU,"Sydney, Australia",mobile,NaN,NaN,NaN

In [4]:
def make_encoding_label_dict(col_unique):
    encoded_dict = {}
    for idx, unique in enumerate(col_unique):
        encoded_dict[unique] = idx + 1

    return encoded_dict


# get new encoding result
def get_newcode(key, label_dict):
    com_len = len(label_dict)
    if key == np.nan:
        return
    else:
        if key in label_dict:
            return label_dict[key]
        else:
            return com_len + 1

In [5]:
df = df.fillna(value = '0')

In [6]:
encoded_action_dict = make_encoding_label_dict(df.action_type.value_counts().index.tolist())
encoded_st_dict = make_encoding_label_dict(df.step.value_counts().index.tolist())
encoded_session_dict = make_encoding_label_dict(df.session_id.value_counts().index.tolist())
encoded_city_dict = make_encoding_label_dict(df.city.value_counts().index.tolist())

In [7]:
df

,user_id,session_id,timestamp,step,action_type,reference,platform,city,device,current_filters,impressions,prices
0,00RL8Z82B2Z1,aff3928535f48,1541037460,1,search for poi,Newtown,AU,"Sydney, Australia",mobile,0,0,0
1,00RL8Z82B2Z1,aff3928535f48,1541037522,2,interaction item image,666856,AU,"Sydney, Australia",mobile,0,0,0
2,00RL8Z82B2Z1,aff3928535f48,1541037522,3,interaction item image,666856,AU,"Sydney, Australia",mobile,0,0,0
3,00RL8Z82B2Z1,aff3928535f48,1541037532,4,interaction item image,666856,AU,"Sydney, Australia",mobile,0,0,0
4,00RL8Z82B2Z1,aff3928535f48,1541037532,5,interaction item image,109038,AU,"Sydney, Australia",mobile,0,0,0
5,00RL8Z82B2Z1,aff3928535f48,1541037532,6,interaction item image,666856,AU,"Sydney, Australia",mobile,0,0,0
6,00RL8Z82B2Z1,aff3928535f48,1541037532,7,interaction item image,109038,AU,"Sydney, Australia",mobile,0,0,0
7,00RL8Z82B2Z1,aff3928535f48,1541037532,8,interaction item image,666856,AU,"Sydney, Australia",mobile,0,0,0
8,00RL8Z82B2Z1,aff3928535f48,1541037542,9,interaction item image,109038,AU,"Sydney, Australia",mobile,0,0,0
9,00RL8Z82B2Z1,aff3928535f48,1541037542,10,interaction item image,109038,AU,"Sydney, Australia",mobile,0,0,0
10,00RL8Z82B2Z1,aff3928535f48,1541037542,11,interaction item image,109038,AU,"Sydney, Australia",mobile,0,0,0
11,00RL8Z82B2Z1,aff3928535f48,1541037542,12,interaction item image,109038,AU,"Sydney, Australia",mobile,0,0,0
12,00RL8Z82B2Z1,aff3928535f48,1541037542,13,interaction item image,109038,AU,"Sydney, Australia",mobile,0,0,0
13,00RL8Z82B2Z1,aff3928535f48,1541037543,14,clickout item,109038,AU,"Sydney, Australia",mobile,0,3400638|1253714|3367857|5100540|1088584|666916...,95|66|501|112|95|100|101|72|82|56|56|143|70|25...
14,00RL8Z82B2Z1,aff3928535f48,1541038469,15,search for poi,Surry Hills,AU,"Sydney, Australia",mobile,0,0,0
15,00RL8Z82B2Z1,aff3928535f48,1541038485,16,clickout item,1257342,AU,"Sydney, Australia",mobile,0,55109|129343|54824|2297972|109014|1257342|1031...,162|25|150|143|101|49|118|131|18|100|101|143|5...
16,02HGRBA06ODU,fa3a53156ae5c,1541030832,1,interaction item info,3377332,BR,"Ubatuba, Brazil",mobile,0,0,0
17,02HGRBA06ODU,fa3a53156ae5c,1541030843,2,interaction item image,3377332,BR,"Ubatuba, Brazil",mobile,0,0,0
18,02HGRBA06ODU,fa3a53156ae5c,1541030843,3,interaction item image,3377332,BR,"Ubatuba, Brazil",mobile,0,0,0
19,02HGRBA06ODU,fa3a53156ae5c,1541030852,4,interaction item info,3377332,BR,"Ubatuba, Brazil",mobile,0,0,0
20,02HGRBA06ODU,fa3a53156ae5c,1541030867,5,interaction item info,3066244,BR,"Ubatuba, Brazil",mobile,0,0,0
21,02HGRBA06ODU,fa3a53156ae5c,1541030877,6,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,0,0,0
22,02HGRBA06ODU,fa3a53156ae5c,1541030877,7,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,0,0,0
23,02HGRBA06ODU,fa3a53156ae5c,1541030887,8,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,0,0,0
24,02HGRBA06ODU,fa3a53156ae5c,1541030887,9,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,0,0,0
25,02HGRBA06ODU,fa3a53156ae5c,1541030887,10,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,0,0,0
26,02HGRBA06ODU,fa3a53156ae5c,1541030897,11,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,0,0,0
27,02HGRBA06ODU,fa3a53156ae5c,1541030897,12,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,0,0,0
28,02HGRBA06ODU,fa3a53156ae5c,1541030897,13,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,0,0,0
29,02HGRBA06ODU,fa3a53156ae5c,1541030897,14,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
469,0O1CTEP95YKQ,af793494b5f84,1541113259,1,change of sort order,interaction sort button,CO,"Las Vegas, USA",mobile,0,0,0
470,0O1CTEP95YKQ,af793494b5f84,1541113276,2,filter selection,Hotel,CO,"Las Vegas, USA",mobile,Hotel|Motel|Resort,0,0
471,0O1CTEP95YKQ,af793494b5f84,1541113276,3,filter selection,Motel,CO,"Las Vegas, USA",mobile,Hotel|Motel|Resort,0,0
472,0O1CTEP95YKQ,af793494b5f84,1541113276,4,filter selection,Resort,CO,"Las Vegas, USA",mobile,Hotel|Motel|Resort,0,0
473,0O1CTEP95YKQ,af793494b5f84,1541113314,5,filter selection,Breakfast Included,CO,"Las Vegas, USA",mobile,Hotel|Motel|Resort|Breakfast Included,0,0
474,0O1CTEP95YKQ,af793494b5f84,1541113324,6,filter selection,Breakfast Included,CO,"Las Vegas, USA",mobile,Hotel|Motel|Resort,0,0
475,0O1CTEP95YKQ,af793494b5f84,1541113325,7,filter selection,Resort,CO,"Las Vegas, USA",mobile,Hotel|Motel,0,0
476,0O1CTEP95YKQ,af793494b5f84,1541113325,8,filter selection,Motel,CO,"Las Vegas, USA",mobile,Hotel,0,0
477,0O1CTEP95YKQ,af793494b5f84,1541113329,9,filter selection,Hotel,CO,"Las Vegas, USA",mobile,0,0,0
478,0O1CTEP95YKQ,af793494b5f84,1541113330,10,filter selection,Breakfast Included,CO,"Las Vegas, USA",mobile,Breakfast Included,0,0
479,0O1CTEP95YKQ,af793494b5f84,1541113350,11,filter selection,Free WiFi (Combined),CO,"Las Vegas, USA",mobile,Breakfast Included|Free WiFi (Combined),0,0
480,0O1CTEP95YKQ,af793494b5f84,1541113352,12,filter selection,Free WiFi (Combined),CO,"Las Vegas, USA",mobile,Breakfast Included,0,0
481,0O1CTEP95YKQ,af793494b5f84,1541113355,13,filter selection,Free WiFi (Combined),CO,"Las Vegas, USA",mobile,Breakfast Included,0,0
482,0O1CTEP95YKQ,af793494b5f84,1541113360,14,filter selection,Breakfast Included,CO,"Las Vegas, USA",mobile,0,0,0
483,0O1CTEP95YKQ,af793494b5f84,1541113366,15,filter selection,Breakfast Included,CO,"Las Vegas, USA",mobile,Breakfast Included,0,0
484,0O1CTEP95YKQ,af793494b5f84,1541113452,16,change of sort order,price only,CO,"Las Vegas, USA",mobile,0,0,0
485,0O1CTEP95YKQ,af793494b5f84,1541113452,17,change of sort order,interaction sort button,CO,"Las Vegas, USA",mobile,0,0,0
486,0O1CTEP95YKQ,af793494b5f84,1541113452,18,filter selection,Sort by Price,CO,"Las Vegas, USA",mobile,Breakfast Included|Sort by Price,0,0
487,0O1CTEP95YKQ,af793494b5f84,1541113474,19,clickout item,63051,CO,"Las Vegas, USA",mobile,Breakfast Included|Sort by Price,69086|8533|925367|58949|61049|8581|8517|77520|...,59|66|78|86|87|90|90|92|93|98|99|100|106|108|1...
488,0O1CTEP95YKQ,af793494b5f84,1541113509,20,clickout item,2851635,CO,"Las Vegas, USA",mobile,Breakfast Included|Sort by Price,69086|8533|925367|58949|61049|8581|8517|77520|...,59|66|78|86|87|90|90|92|93|98|99|100|106|108|1...
489,0O1CTEP95YKQ,af793494b5f84,1541113521,21,interaction item info,62454,CO,"Las Vegas, USA",mobile,0,0,0
490,0O1CTEP95YKQ,af793494b5f84,1541113537,22,clickout item,8602,CO,"Las Vegas, USA",mobile,Breakfast Included|Sort by Price,69086|8533|925367|58949|61049|8581|8517|77520|...,59|66|78|86|87|90|90|92|93|98|99|100|106|108|1...
491,0P3WZY097PQI,2423aea8cde50,1541046025,1,clickout item,488501,US,"Las Vegas, USA",mobile,0,8621|77124|8624|2851635|488501|1810141|72285|8...,1042|370|484|376|1031|871|228|310|255|202|193|...
492,0P3WZY097PQI,2423aea8cde50,1541046141,2,clickout item,8563,US,"Las Vegas, USA",mobile,0,8621|77124|8624|2851635|488501|1810141|72285|8...,1042|370|484|376|1031|871|228|310|255|202|193|...
493,0P3WZY097PQI,2423aea8cde50,1541046260,3,search for destination,"Tioga, USA",US,"Tioga, USA",mobile,0,0,0
494,0P3WZY097PQI,2423aea8cde50,1541046276,4,search for item,8602,US,"Las Vegas, USA",mobile,0,0,0
495,0P3WZY097PQI,2423aea8cde50,1541046333,5,clickout item,2793224,US,"Las Vegas, USA",mobile,0,8602|8568|8621|8561|57049|8564|8586|8577|8589|...,265|125|176|85|152|122|141|136|114|112|188|140...
496,0Q3605EUBZG3,641a409c90fac,1541094556,1,change of sort order,interaction sort button,BR,"Rio de Janeiro, Brazil",mobile,0,0,0
497,0Q3605EUBZG3,641a409c90fac,1541094594,2,change of sort order,interaction sort button,BR,"Rio de Janeiro, Brazil",mobile,0,0,0
498,0Q3605EUBZG3,641a409c90fac,1541094597,3,change of sort order,price and recommended,BR,"Rio de Janeiro, Brazil",mobile,0,0,0

In [8]:
df2 = df
ref = df.reference
df2['e'] = pd.Series(df.reference, index=df.index)

In [9]:
df

,user_id,session_id,timestamp,step,action_type,reference,platform,city,device,current_filters,impressions,prices,e
0,00RL8Z82B2Z1,aff3928535f48,1541037460,1,search for poi,Newtown,AU,"Sydney, Australia",mobile,0,0,0,Newtown
1,00RL8Z82B2Z1,aff3928535f48,1541037522,2,interaction item image,666856,AU,"Sydney, Australia",mobile,0,0,0,666856
2,00RL8Z82B2Z1,aff3928535f48,1541037522,3,interaction item image,666856,AU,"Sydney, Australia",mobile,0,0,0,666856
3,00RL8Z82B2Z1,aff3928535f48,1541037532,4,interaction item image,666856,AU,"Sydney, Australia",mobile,0,0,0,666856
4,00RL8Z82B2Z1,aff3928535f48,1541037532,5,interaction item image,109038,AU,"Sydney, Australia",mobile,0,0,0,109038
5,00RL8Z82B2Z1,aff3928535f48,1541037532,6,interaction item image,666856,AU,"Sydney, Australia",mobile,0,0,0,666856
6,00RL8Z82B2Z1,aff3928535f48,1541037532,7,interaction item image,109038,AU,"Sydney, Australia",mobile,0,0,0,109038
7,00RL8Z82B2Z1,aff3928535f48,1541037532,8,interaction item image,666856,AU,"Sydney, Australia",mobile,0,0,0,666856
8,00RL8Z82B2Z1,aff3928535f48,1541037542,9,interaction item image,109038,AU,"Sydney, Australia",mobile,0,0,0,109038
9,00RL8Z82B2Z1,aff3928535f48,1541037542,10,interaction item image,109038,AU,"Sydney, Australia",mobile,0,0,0,109038
10,00RL8Z82B2Z1,aff3928535f48,1541037542,11,interaction item image,109038,AU,"Sydney, Australia",mobile,0,0,0,109038
11,00RL8Z82B2Z1,aff3928535f48,1541037542,12,interaction item image,109038,AU,"Sydney, Australia",mobile,0,0,0,109038
12,00RL8Z82B2Z1,aff3928535f48,1541037542,13,interaction item image,109038,AU,"Sydney, Australia",mobile,0,0,0,109038
13,00RL8Z82B2Z1,aff3928535f48,1541037543,14,clickout item,109038,AU,"Sydney, Australia",mobile,0,3400638|1253714|3367857|5100540|1088584|666916...,95|66|501|112|95|100|101|72|82|56|56|143|70|25...,109038
14,00RL8Z82B2Z1,aff3928535f48,1541038469,15,search for poi,Surry Hills,AU,"Sydney, Australia",mobile,0,0,0,Surry Hills
15,00RL8Z82B2Z1,aff3928535f48,1541038485,16,clickout item,1257342,AU,"Sydney, Australia",mobile,0,55109|129343|54824|2297972|109014|1257342|1031...,162|25|150|143|101|49|118|131|18|100|101|143|5...,1257342
16,02HGRBA06ODU,fa3a53156ae5c,1541030832,1,interaction item info,3377332,BR,"Ubatuba, Brazil",mobile,0,0,0,3377332
17,02HGRBA06ODU,fa3a53156ae5c,1541030843,2,interaction item image,3377332,BR,"Ubatuba, Brazil",mobile,0,0,0,3377332
18,02HGRBA06ODU,fa3a53156ae5c,1541030843,3,interaction item image,3377332,BR,"Ubatuba, Brazil",mobile,0,0,0,3377332
19,02HGRBA06ODU,fa3a53156ae5c,1541030852,4,interaction item info,3377332,BR,"Ubatuba, Brazil",mobile,0,0,0,3377332
20,02HGRBA06ODU,fa3a53156ae5c,1541030867,5,interaction item info,3066244,BR,"Ubatuba, Brazil",mobile,0,0,0,3066244
21,02HGRBA06ODU,fa3a53156ae5c,1541030877,6,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,0,0,0,3066244
22,02HGRBA06ODU,fa3a53156ae5c,1541030877,7,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,0,0,0,3066244
23,02HGRBA06ODU,fa3a53156ae5c,1541030887,8,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,0,0,0,3066244
24,02HGRBA06ODU,fa3a53156ae5c,1541030887,9,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,0,0,0,3066244
25,02HGRBA06ODU,fa3a53156ae5c,1541030887,10,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,0,0,0,3066244
26,02HGRBA06ODU,fa3a53156ae5c,1541030897,11,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,0,0,0,3066244
27,02HGRBA06ODU,fa3a53156ae5c,1541030897,12,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,0,0,0,3066244
28,02HGRBA06ODU,fa3a53156ae5c,1541030897,13,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,0,0,0,3066244
29,02HGRBA06ODU,fa3a53156ae5c,1541030897,14,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,0,0,0,3066244
...,...,...,...,...,...,...,...,...,...,...,...,...,...
469,0O1CTEP95YKQ,af793494b5f84,1541113259,1,change of sort order,interaction sort button,CO,"Las Vegas, USA",mobile,0,0,0,interaction sort button
470,0O1CTEP95YKQ,af793494b5f84,1541113276,2,filter selection,Hotel,CO,"Las Vegas, USA",mobile,Hotel|Motel|Resort,0,0,Hotel
471,0O1CTEP95YKQ,af793494b5f84,1541113276,3,filter selection,Motel,CO,"Las Vegas, USA",mobile,Hotel|Motel|Resort,0,0,Motel
472,0O1CTEP95YKQ,af793494b5f84,1541113276,4,filter selection,Resort,CO,"Las Vegas, USA",mobile,Hotel|Motel|Resort,0,0,Resort
473,0O1CTEP95YKQ,af793494b5f84,1541113314,5,filter selection,Breakfast Included,CO,"Las Vegas, USA",mobile,Hotel|Motel|Resort|Breakfast Included,0,0,Breakfast Included
474,0O1CTEP95YKQ,af793494b5f84,1541113324,6,filter selection,Breakfast Included,CO,"Las Vegas, USA",mobile,Hotel|Motel|Resort,0,0,Breakfast Included
475,0O1CTEP95YKQ,af793494b5f84,1541113325,7,filter selection,Resort,CO,"Las Vegas, USA",mobile,Hotel|Motel,0,0,Resort
476,0O1CTEP95YKQ,af793494b5f84,1541113325,8,filter selection,Motel,CO,"Las Vegas, USA",mobile,Hotel,0,0,Motel
477,0O1CTEP95YKQ,af793494b5f84,1541113329,9,filter selection,Hotel,CO,"Las Vegas, USA",mobile,0,0,0,Hotel
478,0O1CTEP95YKQ,af793494b5f84,1541113330,10,filter selection,Breakfast Included,CO,"Las Vegas, USA",mobile,Breakfast Included,0,0,Breakfast Included
479,0O1CTEP95YKQ,af793494b5f84,1541113350,11,filter selection,Free WiFi (Combined),CO,"Las Vegas, USA",mobile,Breakfast Included|Free WiFi (Combined),0,0,Free WiFi (Combined)
480,0O1CTEP95YKQ,af793494b5f84,1541113352,12,filter selection,Free WiFi (Combined),CO,"Las Vegas, USA",mobile,Breakfast Included,0,0,Free WiFi (Combined)
481,0O1CTEP95YKQ,af793494b5f84,1541113355,13,filter selection,Free WiFi (Combined),CO,"Las Vegas, USA",mobile,Breakfast Included,0,0,Free WiFi (Combined)
482,0O1CTEP95YKQ,af793494b5f84,1541113360,14,filter selection,Breakfast Included,CO,"Las Vegas, USA",mobile,0,0,0,Breakfast Included
483,0O1CTEP95YKQ,af793494b5f84,1541113366,15,filter selection,Breakfast Included,CO,"Las Vegas, USA",mobile,Breakfast Included,0,0,Breakfast Included
484,0O1CTEP95YKQ,af793494b5f84,1541113452,16,change of sort order,price only,CO,"Las Vegas, USA",mobile,0,0,0,price only
485,0O1CTEP95YKQ,af793494b5f84,1541113452,17,change of sort order,interaction sort button,CO,"Las Vegas, USA",mobile,0,0,0,interaction sort button
486,0O1CTEP95YKQ,af793494b5f84,1541113452,18,filter selection,Sort by Price,CO,"Las Vegas, USA",mobile,Breakfast Included|Sort by Price,0,0,Sort by Price
487,0O1CTEP95YKQ,af793494b5f84,1541113474,19,clickout item,63051,CO,"Las Vegas, USA",mobile,Breakfast Included|Sort by Price,69086|8533|925367|58949|61049|8581|8517|77520|...,59|66|78|86|87|90|90|92|93|98|99|100|106|108|1...,63051
488,0O1CTEP95YKQ,af793494b5f84,1541113509,20,clickout item,2851635,CO,"Las Vegas, USA",mobile,Breakfast Included|Sort by Price,69086|8533|925367|58949|61049|8581|8517|77520|...,59|66|78|86|87|90|90|92|93|98|99|100|106|108|1...,2851635
489,0O1CTEP95YKQ,af793494b5f84,1541113521,21,interaction item info,62454,CO,"Las Vegas, USA",mobile,0,0,0,62454
490,0O1CTEP95YKQ,af793494b5f84,1541113537,22,clickout item,8602,CO,"Las Vegas, USA",mobile,Breakfast Included|Sort by Price,69086|8533|925367|58949|61049|8581|8517|77520|...,59|66|78|86|87|90|90|92|93|98|99|100|106|108|1...,8602
491,0P3WZY097PQI,2423aea8cde50,1541046025,1,clickout item,488501,US,"Las Vegas, USA",mobile,0,8621|77124|8624|2851635|488501|1810141|72285|8...,1042|370|484|376|1031|871|228|310|255|202|193|...,488501
492,0P3WZY097PQI,2423aea8cde50,1541046141,2,clickout item,8563,US,"Las Vegas, USA",mobile,0,8621|77124|8624|2851635|488501|1810141|72285|8...,1042|370|484|376|1031|871|228|310|255|202|193|...,8563
493,0P3WZY097PQI,2423aea8cde50,1541046260,3,search for destination,"Tioga, USA",US,"Tioga, USA",mobile,0,0,0,"Tioga, USA"
494,0P3WZY097PQI,2423aea8cde50,1541046276,4,search for item,8602,US,"Las Vegas, USA",mobile,0,0,0,8602
495,0P3WZY097PQI,2423aea8cde50,1541046333,5,clickout item,2793224,US,"Las Vegas, USA",mobile,0,8602|8568|8621|8561|57049|8564|8586|8577|8589|...,265|125|176|85|152|122|141|136|114|112|188|140...,2793224
496,0Q3605EUBZG3,641a409c90fac,1541094556,1,change of sort order,interaction sort button,BR,"Rio de Janeiro, Brazil",mobile,0,0,0,interaction sort button
497,0Q3605EUBZG3,641a409c90fac,1541094594,2,change of sort order,interaction sort button,BR,"Rio de Janeiro, Brazil",mobile,0,0,0,interaction sort button
498,0Q3605EUBZG3,641a409c90fac,1541094597,3,change of sort order,price and recommended,BR,"Rio de Janeiro, Brazil",mobile,0,0,0,price and recommended

In [10]:
ref = df.reference

In [11]:
ref

0                      Newtown
1                       666856
2                       666856
3                       666856
4                       109038
5                       666856
6                       109038
7                       666856
8                       109038
9                       109038
10                      109038
11                      109038
12                      109038
13                      109038
14                 Surry Hills
15                     1257342
16                     3377332
17                     3377332
18                     3377332
19                     3377332
20                     3066244
21                     3066244
22                     3066244
23                     3066244
24                     3066244
25                     3066244
26                     3066244
27                     3066244
28                     3066244
29                     3066244
                ...
469    interaction sort button
470                      Hotel
471                      Motel
472                     Resort
473         Breakfast Included
474         Breakfast Included
475                     Resort
476                      Motel
477                      Hotel
478         Breakfast Included
479       Free WiFi (Combined)
480       Free WiFi (Combined)
481       Free WiFi (Combined)
482         Breakfast Included
483         Breakfast Included
484                 price only
485    interaction sort button
486              Sort by Price
487                      63051
488                    2851635
489                      62454
490                       8602
491                     488501
492                       8563
493                 Tioga, USA
494                       8602
495                    2793224
496    interaction sort button
497    interaction sort button
498      price and recommended
Name: reference, Length: 499, dtype: object

In [12]:
ref.values

array(['Newtown', '666856', '666856', '666856', '109038', '666856',
       '109038', '666856', '109038', '109038', '109038', '109038',
       '109038', '109038', 'Surry Hills', '1257342', '3377332', '3377332',
       '3377332', '3377332', '3066244', '3066244', '3066244', '3066244',
       '3066244', '3066244', '3066244', '3066244', '3066244', '3066244',
       '3066244', '3066244', '3066244', '3066244', '3066244', '3066244',
       '3066244', '3066244', '3066244', '3066244', '3066244', '3066244',
       '3066244', '3066244', '3066244', '3066244', '3066244', '3066244',
       '3066244', '3066244', '3066244', '3066244', '3066244', '3066244',
       '3066244', '3066244', '3066244', '3066244', '3066244', '3066244',
       '3066244', '3066244', '3066244', '3066244', '3066244', '3066244',
       '3066244', '3066244', '3066244', '3066244', '3066244', '3066244',
       '3066244', '3066244', '3066244', '3066244', '3066244', '3066244',
       '3066244', '3066244', '3066244', '2795374', '2795374', '2795374',
       '2795374', '2795374', '2795374', '2795374', '2795374', '2795374',
       '2795374', '2795374', '2795374', '2795374', '2795374', '2795374',
       '2795374', '2795374', '2795374', '2795374', '2795374', '2795374',
       '2795374', '2795374', '2795374', '2795374', '2795374', '2795374',
       '2795374', '2795374', '2795374', '2795374', '2795374', '2795374',
       '2795374', '2795374', 'London, United Kingdom', 'Covent Garden',
       'Oxford Street', '1032816', '1032816', '1032816', '1032816',
       'Bakersfield, USA', 'Bakersfield, USA', 'Very Good Rating',
       'Hostal (ES)', 'Hotel', 'Motel', 'Resort', '4 Star', '5 Star',
       'Hostal (ES)', 'Hotel', 'Motel', 'Resort', '3 Star', '4 Star',
       '5 Star', '65685', '65685', '65685', '65685', '65685', '65685',
       '65685', '65685', '65685', '65685', '65685', '65685', '65685',
       '65685', '65685', '65685', '65685', '65685', '65685', '65685',
       '65685', '65685', '65685', '65685', '65685', '65685', '65685',
       '65685', '65685', '65685', '65685', '65685', '65685', '65685',
       '65685', '65685', '65685', '65685', '1320460', '749441', '1258184',
       '3143258', '2552514', '2552514', '2552514', '110591',
       'interaction sort button', 'price and recommended', 'Best Value',
       '2557176', '138930', '138930', '138930', '138930', '138930',
       '138930', '138930', '129881', '8561', '8561', '8561', '8561',
       '8561', '8561', '8561', '8561', '8561', '8561', '8561', '8561',
       '8561', '8561', '8561', '8561', '8561', '8561', '8561', '8561',
       '8561', '8561', '8561', '8561', '8561', '8561', '8561', '8561',
       '8561', '8561', '8561', '8561', '8561', '8561',
       'Panama City, Panama', '3176346', '3176346', '3176346', '3176346',
       '2529658', '921237', 'Centre, USA', '9167996', '9167996',
       '9167996', '9167996', '9167996', '9167996', '9167996', '9167996',
       '9167996', '9167996', '9167996', '9167996', '9167996', '9167996',
       '9167996', '9167996', '9167996', 'São Paulo, Brazil',
       'São Paulo, Brazil', 'interaction sort button', '104499', '104499',
       '104499', '4138580', '4138580', '4138580', '4138580', '4138580',
       '4138580', '4138580', '4138580', '4138580', '4138580', '478026',
       '478026', '478026', '4138580', 'Free WiFi (Combined)', '4138580',
       'Seoul Station', '10091602', '10091602', 'Myeongdong', '10091602',
       'Myeongdong', 'Dongdaemun Market', '1394008', '1394008', '5109850',
       '475256', '475256', '10091602', '10091602', '10091602', '6893402',
       '46893', '46893', '3191226', '9387652', '2564964', '2564964',
       '2564964', '2896408', '2896408', '2896408', '3484132', '3484132',
       '3484132', '3484132', '3484132', '3484132', '3484132', '3484132',
       '3484132', '3484132', '3484132', '3484132', '3484132', '3484132',
       '3484132', '3484132', '3484132', '3484132', '3484132', '3484132',
       '3484132', '3484132', '3484132', '3484132', '6696574',
       'Ocean Park', '2395594', '2395594', '2395594', '2395594',
       '2395594', '2395594', '2395594', '2395594', '2395594', '2395594',
       '2395594', '2395594', '2395594', '2395594', '2395594', '2395594',
       '2395594', '2395594', '2395594', '2395594', '2395594', '2395594',
       '2395594', '2395594', '2395594', 'Free WiFi (Combined)',
       'Breakfast Included', '1045290', '1045290', '1045290', '1045290',
       '1045290', '1045290', '1045290', '1045290', '1045290', '1045290',
       '1045290', '1045290', '1045290', '1045290', '1045290', '1045290',
       '1045290', '1045290', '1045290', '1045290', '1045290', '1045290',
       '1045290', '1045290', '1045290', '1045290', '1045290', '1045290',
       '1045290', '1045290', '1045290', '1045290', '1045290', '1045290',
       '1045290', '1045290', '1045290', '320366', '320366', '320366',
       '320366', '320366', '320366', '320366', '320366', '320366',
       '320366', '320366', '320366', '320366', '320366', '320366',
       '320366', '320366', '320366', '320366', '320366', '320366',
       '320366', '320366', '320366', '320366', '320366', '320366',
       '320366', '320366', '320366', '320366', '320366', '320366',
       '320366', '320366', '320366', '320366', '1091180', '1091180',
       '1091180', '1091180', '1091180', '1091180', '1091180', '1091180',
       '1091180', '1091180', '1091180', '1091180', '1091180', '1091180',
       '1091180', '1091180', '1091180', '1091180', '1091180', '1091180',
       '1091180', '1091180', '1091180', '1091180', '3404929', '3404929',
       '3404929', '3404929', '3404929', '3404929', '3404929', '3404929',
       '3404929', '3404929', '3404929', '3404929', '3135752', '9164598',
       'interaction sort button', 'Hotel', 'Motel', 'Resort',
       'Breakfast Included', 'Breakfast Included', 'Resort', 'Motel',
       'Hotel', 'Breakfast Included', 'Free WiFi (Combined)',
       'Free WiFi (Combined)', 'Free WiFi (Combined)',
       'Breakfast Included', 'Breakfast Included', 'price only',
       'interaction sort button', 'Sort by Price', '63051', '2851635',
       '62454', '8602', '488501', '8563', 'Tioga, USA', '8602', '2793224',
       'interaction sort button', 'interaction sort button',
       'price and recommended'], dtype=object)

In [13]:
pastActivity = np.insert(ref.values, 0, '0')

In [14]:
df2['past_activity'] = pd.Series(pastActivity[:499], index=df.index)

In [15]:
df

,user_id,session_id,timestamp,step,action_type,reference,platform,city,device,current_filters,impressions,prices,e,past_activity
0,00RL8Z82B2Z1,aff3928535f48,1541037460,1,search for poi,Newtown,AU,"Sydney, Australia",mobile,0,0,0,Newtown,0
1,00RL8Z82B2Z1,aff3928535f48,1541037522,2,interaction item image,666856,AU,"Sydney, Australia",mobile,0,0,0,666856,Newtown
2,00RL8Z82B2Z1,aff3928535f48,1541037522,3,interaction item image,666856,AU,"Sydney, Australia",mobile,0,0,0,666856,666856
3,00RL8Z82B2Z1,aff3928535f48,1541037532,4,interaction item image,666856,AU,"Sydney, Australia",mobile,0,0,0,666856,666856
4,00RL8Z82B2Z1,aff3928535f48,1541037532,5,interaction item image,109038,AU,"Sydney, Australia",mobile,0,0,0,109038,666856
5,00RL8Z82B2Z1,aff3928535f48,1541037532,6,interaction item image,666856,AU,"Sydney, Australia",mobile,0,0,0,666856,109038
6,00RL8Z82B2Z1,aff3928535f48,1541037532,7,interaction item image,109038,AU,"Sydney, Australia",mobile,0,0,0,109038,666856
7,00RL8Z82B2Z1,aff3928535f48,1541037532,8,interaction item image,666856,AU,"Sydney, Australia",mobile,0,0,0,666856,109038
8,00RL8Z82B2Z1,aff3928535f48,1541037542,9,interaction item image,109038,AU,"Sydney, Australia",mobile,0,0,0,109038,666856
9,00RL8Z82B2Z1,aff3928535f48,1541037542,10,interaction item image,109038,AU,"Sydney, Australia",mobile,0,0,0,109038,109038
10,00RL8Z82B2Z1,aff3928535f48,1541037542,11,interaction item image,109038,AU,"Sydney, Australia",mobile,0,0,0,109038,109038
11,00RL8Z82B2Z1,aff3928535f48,1541037542,12,interaction item image,109038,AU,"Sydney, Australia",mobile,0,0,0,109038,109038
12,00RL8Z82B2Z1,aff3928535f48,1541037542,13,interaction item image,109038,AU,"Sydney, Australia",mobile,0,0,0,109038,109038
13,00RL8Z82B2Z1,aff3928535f48,1541037543,14,clickout item,109038,AU,"Sydney, Australia",mobile,0,3400638|1253714|3367857|5100540|1088584|666916...,95|66|501|112|95|100|101|72|82|56|56|143|70|25...,109038,109038
14,00RL8Z82B2Z1,aff3928535f48,1541038469,15,search for poi,Surry Hills,AU,"Sydney, Australia",mobile,0,0,0,Surry Hills,109038
15,00RL8Z82B2Z1,aff3928535f48,1541038485,16,clickout item,1257342,AU,"Sydney, Australia",mobile,0,55109|129343|54824|2297972|109014|1257342|1031...,162|25|150|143|101|49|118|131|18|100|101|143|5...,1257342,Surry Hills
16,02HGRBA06ODU,fa3a53156ae5c,1541030832,1,interaction item info,3377332,BR,"Ubatuba, Brazil",mobile,0,0,0,3377332,1257342
17,02HGRBA06ODU,fa3a53156ae5c,1541030843,2,interaction item image,3377332,BR,"Ubatuba, Brazil",mobile,0,0,0,3377332,3377332
18,02HGRBA06ODU,fa3a53156ae5c,1541030843,3,interaction item image,3377332,BR,"Ubatuba, Brazil",mobile,0,0,0,3377332,3377332
19,02HGRBA06ODU,fa3a53156ae5c,1541030852,4,interaction item info,3377332,BR,"Ubatuba, Brazil",mobile,0,0,0,3377332,3377332
20,02HGRBA06ODU,fa3a53156ae5c,1541030867,5,interaction item info,3066244,BR,"Ubatuba, Brazil",mobile,0,0,0,3066244,3377332
21,02HGRBA06ODU,fa3a53156ae5c,1541030877,6,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,0,0,0,3066244,3066244
22,02HGRBA06ODU,fa3a53156ae5c,1541030877,7,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,0,0,0,3066244,3066244
23,02HGRBA06ODU,fa3a53156ae5c,1541030887,8,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,0,0,0,3066244,3066244
24,02HGRBA06ODU,fa3a53156ae5c,1541030887,9,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,0,0,0,3066244,3066244
25,02HGRBA06ODU,fa3a53156ae5c,1541030887,10,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,0,0,0,3066244,3066244
26,02HGRBA06ODU,fa3a53156ae5c,1541030897,11,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,0,0,0,3066244,3066244
27,02HGRBA06ODU,fa3a53156ae5c,1541030897,12,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,0,0,0,3066244,3066244
28,02HGRBA06ODU,fa3a53156ae5c,1541030897,13,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,0,0,0,3066244,3066244
29,02HGRBA06ODU,fa3a53156ae5c,1541030897,14,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,0,0,0,3066244,3066244
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
469,0O1CTEP95YKQ,af793494b5f84,1541113259,1,change of sort order,interaction sort button,CO,"Las Vegas, USA",mobile,0,0,0,interaction sort button,9164598
470,0O1CTEP95YKQ,af793494b5f84,1541113276,2,filter selection,Hotel,CO,"Las Vegas, USA",mobile,Hotel|Motel|Resort,0,0,Hotel,interaction sort button
471,0O1CTEP95YKQ,af793494b5f84,1541113276,3,filter selection,Motel,CO,"Las Vegas, USA",mobile,Hotel|Motel|Resort,0,0,Motel,Hotel
472,0O1CTEP95YKQ,af793494b5f84,1541113276,4,filter selection,Resort,CO,"Las Vegas, USA",mobile,Hotel|Motel|Resort,0,0,Resort,Motel
473,0O1CTEP95YKQ,af793494b5f84,1541113314,5,filter selection,Breakfast Included,CO,"Las Vegas, USA",mobile,Hotel|Motel|Resort|Breakfast Included,0,0,Breakfast Included,Resort
474,0O1CTEP95YKQ,af793494b5f84,1541113324,6,filter selection,Breakfast Included,CO,"Las Vegas, USA",mobile,Hotel|Motel|Resort,0,0,Breakfast Included,Breakfast Included
475,0O1CTEP95YKQ,af793494b5f84,1541113325,7,filter selection,Resort,CO,"Las Vegas, USA",mobile,Hotel|Motel,0,0,Resort,Breakfast Included
476,0O1CTEP95YKQ,af793494b5f84,1541113325,8,filter selection,Motel,CO,"Las Vegas, USA",mobile,Hotel,0,0,Motel,Resort
477,0O1CTEP95YKQ,af793494b5f84,1541113329,9,filter selection,Hotel,CO,"Las Vegas, USA",mobile,0,0,0,Hotel,Motel
478,0O1CTEP95YKQ,af793494b5f84,1541113330,10,filter selection,Breakfast Included,CO,"Las Vegas, USA",mobile,Breakfast Included,0,0,Breakfast Included,Hotel
479,0O1CTEP95YKQ,af793494b5f84,1541113350,11,filter selection,Free WiFi (Combined),CO,"Las Vegas, USA",mobile,Breakfast Included|Free WiFi (Combined),0,0,Free WiFi (Combined),Breakfast Included
480,0O1CTEP95YKQ,af793494b5f84,1541113352,12,filter selection,Free WiFi (Combined),CO,"Las Vegas, USA",mobile,Breakfast Included,0,0,Free WiFi (Combined),Free WiFi (Combined)
481,0O1CTEP95YKQ,af793494b5f84,1541113355,13,filter selection,Free WiFi (Combined),CO,"Las Vegas, USA",mobile,Breakfast Included,0,0,Free WiFi (Combined),Free WiFi (Combined)
482,0O1CTEP95YKQ,af793494b5f84,1541113360,14,filter selection,Breakfast Included,CO,"Las Vegas, USA",mobile,0,0,0,Breakfast Included,Free WiFi (Combined)
483,0O1CTEP95YKQ,af793494b5f84,1541113366,15,filter selection,Breakfast Included,CO,"Las Vegas, USA",mobile,Breakfast Included,0,0,Breakfast Included,Breakfast Included
484,0O1CTEP95YKQ,af793494b5f84,1541113452,16,change of sort order,price only,CO,"Las Vegas, USA",mobile,0,0,0,price only,Breakfast Included
485,0O1CTEP95YKQ,af793494b5f84,1541113452,17,change of sort order,interaction sort button,CO,"Las Vegas, USA",mobile,0,0,0,interaction sort button,price only
486,0O1CTEP95YKQ,af793494b5f84,1541113452,18,filter selection,Sort by Price,CO,"Las Vegas, USA",mobile,Breakfast Included|Sort by Price,0,0,Sort by Price,interaction sort button
487,0O1CTEP95YKQ,af793494b5f84,1541113474,19,clickout item,63051,CO,"Las Vegas, USA",mobile,Breakfast Included|Sort by Price,69086|8533|925367|58949|61049|8581|8517|77520|...,59|66|78|86|87|90|90|92|93|98|99|100|106|108|1...,63051,Sort by Price
488,0O1CTEP95YKQ,af793494b5f84,1541113509,20,clickout item,2851635,CO,"Las Vegas, USA",mobile,Breakfast Included|Sort by Price,69086|8533|925367|58949|61049|8581|8517|77520|...,59|66|78|86|87|90|90|92|93|98|99|100|106|108|1...,2851635,63051
489,0O1CTEP95YKQ,af793494b5f84,1541113521,21,interaction item info,62454,CO,"Las Vegas, USA",mobile,0,0,0,62454,2851635
490,0O1CTEP95YKQ,af793494b5f84,1541113537,22,clickout item,8602,CO,"Las Vegas, USA",mobile,Breakfast Included|Sort by Price,69086|8533|925367|58949|61049|8581|8517|77520|...,59|66|78|86|87|90|90|92|93|98|99|100|106|108|1...,8602,62454
491,0P3WZY097PQI,2423aea8cde50,1541046025,1,clickout item,488501,US,"Las Vegas, USA",mobile,0,8621|77124|8624|2851635|488501|1810141|72285|8...,1042|370|484|376|1031|871|228|310|255|202|193|...,488501,8602
492,0P3WZY097PQI,2423aea8cde50,1541046141,2,clickout item,8563,US,"Las Vegas, USA",mobile,0,8621|77124|8624|2851635|488501|1810141|72285|8...,1042|370|484|376|1031|871|228|310|255|202|193|...,8563,488501
493,0P3WZY097PQI,2423aea8cde50,1541046260,3,search for destination,"Tioga, USA",US,"Tioga, USA",mobile,0,0,0,"Tioga, USA",8563
494,0P3WZY097PQI,2423aea8cde50,1541046276,4,search for item,8602,US,"Las Vegas, USA",mobile,0,0,0,8602,"Tioga, USA"
495,0P3WZY097PQI,2423aea8cde50,1541046333,5,clickout item,2793224,US,"Las Vegas, USA",mobile,0,8602|8568|8621|8561|57049|8564|8586|8577|8589|...,265|125|176|85|152|122|141|136|114|112|188|140...,2793224,8602
496,0Q3605EUBZG3,641a409c90fac,1541094556,1,change of sort order,interaction sort button,BR,"Rio de Janeiro, Brazil",mobile,0,0,0,interaction sort button,2793224
497,0Q3605EUBZG3,641a409c90fac,1541094594,2,change of sort order,interaction sort button,BR,"Rio de Janeiro, Brazil",mobile,0,0,0,interaction sort button,interaction sort button
498,0Q3605EUBZG3,641a409c90fac,1541094597,3,change of sort order,price and recommended,BR,"Rio de Janeiro, Brazil",mobile,0,0,0,price and recommended,interaction sort button

In [16]:
np.chararray.isnumeric('asd') == True

False

In [17]:
past = 0
ps = pastActivity[:499]
ps2 = np.zeros(len(ps))
ps3 = df.step.values

In [18]:
for i in range(len(ps)):
    elem = ps[i]
    if np.chararray.isnumeric(elem) == True:
        past = elem
        if ps3[i] == 1: # still a number not a str i didnt change it 
            #print('stj')
            past = 0
        ps2[i] = past
        continue 
    else:
        if ps3[i] == 1: # still a number not a str i didnt change it 
            #print('stj')
            past = 0
        ps2[i] = past

In [19]:
ps2 =ps2.astype('int64')
ps2 = ps2.astype('str')

In [20]:
ps2

array(['0', '0', '666856', '666856', '666856', '109038', '666856',
       '109038', '666856', '109038', '109038', '109038', '109038',
       '109038', '109038', '109038', '0', '3377332', '3377332', '3377332',
       '3377332', '3066244', '3066244', '3066244', '3066244', '3066244',
       '3066244', '3066244', '3066244', '3066244', '3066244', '3066244',
       '3066244', '3066244', '3066244', '3066244', '3066244', '3066244',
       '3066244', '3066244', '3066244', '3066244', '3066244', '3066244',
       '3066244', '3066244', '3066244', '3066244', '3066244', '3066244',
       '3066244', '3066244', '3066244', '3066244', '3066244', '3066244',
       '3066244', '3066244', '3066244', '3066244', '3066244', '3066244',
       '3066244', '3066244', '3066244', '3066244', '3066244', '3066244',
       '3066244', '3066244', '3066244', '3066244', '3066244', '3066244',
       '3066244', '3066244', '3066244', '3066244', '3066244', '3066244',
       '3066244', '0', '2795374', '2795374', '2795374', '2795374',
       '2795374', '2795374', '2795374', '2795374', '2795374', '2795374',
       '2795374', '2795374', '2795374', '2795374', '2795374', '2795374',
       '2795374', '2795374', '2795374', '2795374', '2795374', '2795374',
       '2795374', '2795374', '2795374', '2795374', '2795374', '2795374',
       '2795374', '2795374', '2795374', '2795374', '2795374', '2795374',
       '0', '0', '0', '0', '1032816', '1032816', '1032816', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '0', '65685', '65685', '65685', '65685', '65685', '65685', '65685',
       '65685', '65685', '65685', '65685', '65685', '65685', '65685',
       '65685', '65685', '65685', '65685', '65685', '65685', '65685',
       '65685', '65685', '65685', '65685', '65685', '65685', '65685',
       '65685', '65685', '65685', '65685', '65685', '65685', '65685',
       '65685', '65685', '65685', '0', '749441', '1258184', '0',
       '2552514', '2552514', '0', '0', '0', '0', '0', '2557176', '138930',
       '138930', '138930', '138930', '138930', '138930', '0', '0', '8561',
       '8561', '8561', '8561', '8561', '8561', '8561', '8561', '8561',
       '8561', '8561', '8561', '8561', '8561', '8561', '8561', '8561',
       '8561', '8561', '8561', '8561', '8561', '8561', '8561', '8561',
       '8561', '8561', '8561', '8561', '8561', '8561', '8561', '8561',
       '0', '0', '3176346', '3176346', '3176346', '3176346', '0',
       '921237', '0', '9167996', '9167996', '9167996', '9167996',
       '9167996', '9167996', '9167996', '9167996', '9167996', '9167996',
       '9167996', '9167996', '9167996', '9167996', '9167996', '9167996',
       '0', '0', '0', '0', '104499', '104499', '0', '4138580', '4138580',
       '4138580', '4138580', '4138580', '4138580', '4138580', '4138580',
       '4138580', '4138580', '478026', '478026', '478026', '4138580',
       '4138580', '0', '0', '10091602', '10091602', '10091602',
       '10091602', '10091602', '10091602', '1394008', '1394008',
       '5109850', '475256', '475256', '10091602', '10091602', '10091602',
       '0', '46893', '46893', '0', '9387652', '2564964', '2564964',
       '2564964', '2896408', '2896408', '2896408', '3484132', '3484132',
       '3484132', '3484132', '3484132', '3484132', '3484132', '3484132',
       '3484132', '3484132', '3484132', '3484132', '3484132', '3484132',
       '3484132', '3484132', '3484132', '3484132', '3484132', '3484132',
       '3484132', '3484132', '3484132', '3484132', '0', '0', '2395594',
       '2395594', '2395594', '2395594', '2395594', '2395594', '2395594',
       '2395594', '2395594', '2395594', '2395594', '2395594', '2395594',
       '2395594', '2395594', '2395594', '2395594', '2395594', '2395594',
       '2395594', '2395594', '2395594', '2395594', '2395594', '0', '0',
       '0', '1045290', '1045290', '1045290', '1045290', '1045290',
       '1045290', '1045290', '1045290', '1045290', '1045290', '1045290',
       '1045290', '1045290', '1045290', '1045290', '1045290', '1045290',
       '1045290', '1045290', '1045290', '1045290', '1045290', '1045290',
       '1045290', '1045290', '1045290', '1045290', '1045290', '1045290',
       '1045290', '1045290', '1045290', '1045290', '1045290', '1045290',
       '1045290', '1045290', '320366', '320366', '320366', '320366',
       '320366', '320366', '320366', '320366', '320366', '320366',
       '320366', '320366', '320366', '320366', '320366', '320366',
       '320366', '320366', '320366', '320366', '320366', '320366',
       '320366', '320366', '320366', '320366', '320366', '320366',
       '320366', '320366', '320366', '320366', '320366', '320366',
       '320366', '320366', '320366', '1091180', '1091180', '1091180',
       '1091180', '1091180', '1091180', '1091180', '1091180', '1091180',
       '1091180', '1091180', '1091180', '1091180', '1091180', '1091180',
       '1091180', '1091180', '1091180', '1091180', '1091180', '1091180',
       '1091180', '1091180', '1091180', '3404929', '3404929', '3404929',
       '3404929', '3404929', '3404929', '3404929', '3404929', '3404929',
       '3404929', '3404929', '3404929', '0', '0', '0', '0', '0', '0', '0',
       '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0',
       '63051', '2851635', '62454', '0', '488501', '8563', '8563', '8602',
       '0', '0', '0'], dtype='<U21')

In [21]:
dfA = df[['session_id', 'step', 'city','action_type', 'reference', 'past_activity']]
dfA.head()

,session_id,step,city,action_type,reference,past_activity
0,aff3928535f48,1,"Sydney, Australia",search for poi,Newtown,0
1,aff3928535f48,2,"Sydney, Australia",interaction item image,666856,Newtown
2,aff3928535f48,3,"Sydney, Australia",interaction item image,666856,666856
3,aff3928535f48,4,"Sydney, Australia",interaction item image,666856,666856
4,aff3928535f48,5,"Sydney, Australia",interaction item image,109038,666856

In [22]:
dfA.shape

(499, 6)

In [23]:
prop = pd.read_csv("property_onehot_sum.csv")
prop.head()
prop.shape

(927142, 158)

In [26]:
prop.head()

,item_id,1 Star,2 Star,3 Star,4 Star,5 Star,Accessible Hotel,Accessible Parking,Adults Only,Air Conditioning,...,Terrace (Hotel),Theme Hotel,Towels,Very Good Rating,Volleyball,Washing Machine,Water Slide,Wheelchair Accessible,WiFi (Public Areas),WiFi (Rooms)
0,5001,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,1
1,5002,0,0,0,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,1,1
2,5003,0,0,0,1,0,1,0,0,1,...,1,0,1,1,0,0,0,1,1,1
3,5004,0,0,0,1,0,0,0,0,0,...,1,0,0,1,0,0,0,1,1,1
4,5005,0,0,1,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0

In [49]:
dfA2 = dfA.loc[dfA.reference.str.isnumeric() == True]
dfA2.head()

,session_id,step,city,action_type,reference,past_activity
1,aff3928535f48,2,"Sydney, Australia",interaction item image,666856,Newtown
2,aff3928535f48,3,"Sydney, Australia",interaction item image,666856,666856
3,aff3928535f48,4,"Sydney, Australia",interaction item image,666856,666856
4,aff3928535f48,5,"Sydney, Australia",interaction item image,109038,666856
5,aff3928535f48,6,"Sydney, Australia",interaction item image,666856,109038

In [130]:
dfA3 = dfA2.loc[dfA2.past_activity.str.isnumeric() == True]
dfA3.head()

,session_id,step,city,action_type,reference,past_activity
2,aff3928535f48,3,"Sydney, Australia",interaction item image,666856,666856
3,aff3928535f48,4,"Sydney, Australia",interaction item image,666856,666856
4,aff3928535f48,5,"Sydney, Australia",interaction item image,109038,666856
5,aff3928535f48,6,"Sydney, Australia",interaction item image,666856,109038
6,aff3928535f48,7,"Sydney, Australia",interaction item image,109038,666856

In [131]:
dfA4 = dfA3[['reference','past_activity']]
dfA4.head()

  reference past_activity
2    666856        666856
3    666856        666856
4    109038        666856
5    666856        109038
6    109038        666856

In [132]:
two_hotels = np.asarray(dfA4)

In [133]:
two_hotels[:3]

array([['666856', '666856'],
       ['666856', '666856'],
       ['109038', '666856']], dtype=object)

In [134]:
prop[prop.item_id == int(two_hotels[0,0])].values[0,1:]    # 0, 1: because we need to omit the itemid in the db

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 1], dtype=int64)

# Now change the [ current hotel, past ] into [current property, past ]

In [135]:
a = [prop[prop.item_id == int(two_hotels[2,0])].values[0,1:]  ,prop[prop.item_id == int(two_hotels[2,1])].values[0,1:]  ]
a = np.asarray(a)
a

array([[0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
        0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
        0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
        1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
        1, 1, 1]], dtype=int64)

In [136]:
two_hotels.shape[0]

424

# changed to past->current , label will the next layer's current

In [90]:
two_hotels_vec = [ [prop[prop.item_id == int(two_hotels[i,1])].values[0,1:]  ,prop[prop.item_id == int(two_hotels[i,0])].values[0,1:] ] for i in range(two_hotels.shape[0])]

In [91]:
two_hotels_vec = np.asarray(two_hotels_vec)
two_hotels_vec[2]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
        1, 1, 1],
       [0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
        1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,
        1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
        0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
        0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
        1, 1, 1]], dtype=int64)

# past-> cur -> future (next current but if the session changed then itself

In [137]:
dfA4 = dfA3[['step','past_activity','reference']]
dfA4.head()

   step past_activity reference
2     3        666856    666856
3     4        666856    666856
4     5        666856    109038
5     6        109038    666856
6     7        666856    109038

In [138]:
future_activity = np.array(dfA3.reference)

In [139]:
future_activity = np.delete(future_activity,0)
future_activity = np.insert(future_activity,len(future_activity),'0')

In [140]:
dfA4['future_activity'] = pd.Series(future_activity, index=dfA4.index)

C:\Users\Jee\Anaconda3\envs\py36\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [141]:
nextstep = np.array(dfA3.step)
nextstep = np.delete(nextstep,0)
nextstep = np.insert(np.array(nextstep),len(nextstep),0)

In [144]:
dfA4['nextstep'] = pd.Series(nextstep, index=dfA4.index)

C:\Users\Jee\Anaconda3\envs\py36\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [179]:
dfA4['samesession'] = dfA4.step < dfA4.nextstep

In [181]:
dfA4.head()

   step past_activity reference future_activity  nextstep  samesession
2     3        666856    666856          666856         4         True
3     4        666856    666856          109038         5         True
4     5        666856    109038          666856         6         True
5     6        109038    666856          109038         7         True
6     7        666856    109038          666856         8         True

In [189]:
dfA4['future'] = np.where(dfA4['samesession']== True, dfA4.future_activity,dfA4.reference)

In [190]:
dfA4

,step,past_activity,reference,future_activity,nextstep,samesession,future
2,3,666856,666856,666856,4,True,666856
3,4,666856,666856,109038,5,True,109038
4,5,666856,109038,666856,6,True,666856
5,6,109038,666856,109038,7,True,109038
6,7,666856,109038,666856,8,True,666856
7,8,109038,666856,109038,9,True,109038
8,9,666856,109038,109038,10,True,109038
9,10,109038,109038,109038,11,True,109038
10,11,109038,109038,109038,12,True,109038
11,12,109038,109038,109038,13,True,109038
12,13,109038,109038,109038,14,True,109038
13,14,109038,109038,3377332,1,False,109038
16,1,1257342,3377332,3377332,2,True,3377332
17,2,3377332,3377332,3377332,3,True,3377332
18,3,3377332,3377332,3377332,4,True,3377332
19,4,3377332,3377332,3066244,5,True,3066244
20,5,3377332,3066244,3066244,6,True,3066244
21,6,3066244,3066244,3066244,7,True,3066244
22,7,3066244,3066244,3066244,8,True,3066244
23,8,3066244,3066244,3066244,9,True,3066244
24,9,3066244,3066244,3066244,10,True,3066244
25,10,3066244,3066244,3066244,11,True,3066244
26,11,3066244,3066244,3066244,12,True,3066244
27,12,3066244,3066244,3066244,13,True,3066244
28,13,3066244,3066244,3066244,14,True,3066244
29,14,3066244,3066244,3066244,15,True,3066244
30,15,3066244,3066244,3066244,16,True,3066244
31,16,3066244,3066244,3066244,17,True,3066244
32,17,3066244,3066244,3066244,18,True,3066244
33,18,3066244,3066244,3066244,19,True,3066244
...,...,...,...,...,...,...,...
445,91,1091180,1091180,1091180,92,True,1091180
446,92,1091180,1091180,1091180,93,True,1091180
447,93,1091180,1091180,1091180,94,True,1091180
448,94,1091180,1091180,1091180,95,True,1091180
449,95,1091180,1091180,1091180,96,True,1091180
450,96,1091180,1091180,1091180,97,True,1091180
451,97,1091180,1091180,1091180,98,True,1091180
452,98,1091180,1091180,1091180,99,True,1091180
453,99,1091180,1091180,1091180,100,True,1091180
454,100,1091180,1091180,3404929,101,True,3404929
455,101,1091180,3404929,3404929,102,True,3404929
456,102,3404929,3404929,3404929,103,True,3404929
457,103,3404929,3404929,3404929,104,True,3404929
458,104,3404929,3404929,3404929,105,True,3404929
459,105,3404929,3404929,3404929,106,True,3404929
460,106,3404929,3404929,3404929,107,True,3404929
461,107,3404929,3404929,3404929,108,True,3404929
462,108,3404929,3404929,3404929,109,True,3404929
463,109,3404929,3404929,3404929,110,True,3404929
464,110,3404929,3404929,3404929,111,True,3404929
465,111,3404929,3404929,3404929,112,True,3404929
466,112,3404929,3404929,3135752,113,True,3135752
467,113,3404929,3135752,9164598,1,False,3135752
468,1,3135752,9164598,2851635,20,True,2851635
488,20,63051,2851635,62454,21,True,62454
489,21,2851635,62454,8602,22,True,8602
490,22,62454,8602,488501,1,False,8602
491,1,8602,488501,8563,2,True,8563
492,2,488501,8563,2793224,5,True,2793224
495,5,8602,2793224,0,0,False,2793224

In [192]:
dfA5 = dfA4[['past_activity','reference','future']]

In [197]:
three_hotels = np.asarray(dfA5)

In [200]:
three_hotels_vec = [ [prop[prop.item_id == int(three_hotels[i,0])].values[0,1:]  ,prop[prop.item_id == int(three_hotels[i,1])].values[0,1:] ,prop[prop.item_id == int(three_hotels[i,2])].values[0,1:] ] for i in range(three_hotels.shape[0])]