In [2]:
import os
import pandas as pd
import numpy as np

In [3]:
train = pd.read_csv("train.csv")

In [4]:
session_t = train.drop_duplicates(["action_type","reference"], "first")
session_t

,user_id,session_id,timestamp,step,action_type,reference,platform,city,device,current_filters,impressions,prices
0,00RL8Z82B2Z1,aff3928535f48,1541037460,1,search for poi,Newtown,AU,"Sydney, Australia",mobile,NaN,NaN,NaN
1,00RL8Z82B2Z1,aff3928535f48,1541037522,2,interaction item image,666856,AU,"Sydney, Australia",mobile,NaN,NaN,NaN
4,00RL8Z82B2Z1,aff3928535f48,1541037532,5,interaction item image,109038,AU,"Sydney, Australia",mobile,NaN,NaN,NaN
13,00RL8Z82B2Z1,aff3928535f48,1541037543,14,clickout item,109038,AU,"Sydney, Australia",mobile,NaN,3400638|1253714|3367857|5100540|1088584|666916...,95|66|501|112|95|100|101|72|82|56|56|143|70|25...
14,00RL8Z82B2Z1,aff3928535f48,1541038469,15,search for poi,Surry Hills,AU,"Sydney, Australia",mobile,NaN,NaN,NaN
15,00RL8Z82B2Z1,aff3928535f48,1541038485,16,clickout item,1257342,AU,"Sydney, Australia",mobile,NaN,55109|129343|54824|2297972|109014|1257342|1031...,162|25|150|143|101|49|118|131|18|100|101|143|5...
16,02HGRBA06ODU,fa3a53156ae5c,1541030832,1,interaction item info,3377332,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN
17,02HGRBA06ODU,fa3a53156ae5c,1541030843,2,interaction item image,3377332,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN
20,02HGRBA06ODU,fa3a53156ae5c,1541030867,5,interaction item info,3066244,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN
21,02HGRBA06ODU,fa3a53156ae5c,1541030877,6,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN
62,02HGRBA06ODU,fa3a53156ae5c,1541031044,47,interaction item deals,3066244,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN
81,02SRUT1NQYH1,3599a6f709eab,1541063730,1,interaction item image,2795374,FI,"Krakow, Poland",mobile,NaN,NaN,NaN
114,02SRUT1NQYH1,3599a6f709eab,1541063863,34,interaction item info,2795374,FI,"Krakow, Poland",mobile,NaN,NaN,NaN
115,02SRUT1NQYH1,3599a6f709eab,1541063864,35,clickout item,2795374,FI,"Krakow, Poland",mobile,NaN,2795374|5582964|1088390|2781070|1258068|127196...,64|54|36|121|76|81|92|40|73|52|98|104|56|414|6...
116,03K8AXBL4BX2,ec139e10b9238,1541100038,1,search for destination,"London, United Kingdom",UK,"London, United Kingdom",desktop,NaN,NaN,NaN
117,03K8AXBL4BX2,ec139e10b9238,1541100132,2,search for poi,Covent Garden,UK,"London, United Kingdom",desktop,NaN,NaN,NaN
118,03K8AXBL4BX2,ec139e10b9238,1541100193,3,search for poi,Oxford Street,UK,"London, United Kingdom",desktop,NaN,NaN,NaN
119,03K8AXBL4BX2,ec139e10b9238,1541100314,4,interaction item image,1032816,UK,"London, United Kingdom",desktop,NaN,NaN,NaN
121,03K8AXBL4BX2,ec139e10b9238,1541100322,6,clickout item,1032816,UK,"London, United Kingdom",desktop,NaN,12693|46363|81657|18448|47687|152913|18417|927...,104|92|100|103|102|104|72|85|81|75|107|86|98|8...
123,03P4VFKK12UO,325fafb5fa450,1541107285,1,search for destination,"Bakersfield, USA",US,"Bakersfield, USA",desktop,NaN,NaN,NaN
125,03P4VFKK12UO,325fafb5fa450,1541107336,3,filter selection,Very Good Rating,US,"Bakersfield, USA",desktop,Very Good Rating,NaN,NaN
126,03P4VFKK12UO,325fafb5fa450,1541107366,4,filter selection,Hostal (ES),US,"Bakersfield, USA",desktop,Very Good Rating|5 Star|4 Star|Hotel|Motel|Res...,NaN,NaN
127,03P4VFKK12UO,325fafb5fa450,1541107366,5,filter selection,Hotel,US,"Bakersfield, USA",desktop,Very Good Rating|5 Star|4 Star|Hotel|Motel|Res...,NaN,NaN
128,03P4VFKK12UO,325fafb5fa450,1541107366,6,filter selection,Motel,US,"Bakersfield, USA",desktop,Very Good Rating|5 Star|4 Star|Hotel|Motel|Res...,NaN,NaN
129,03P4VFKK12UO,325fafb5fa450,1541107366,7,filter selection,Resort,US,"Bakersfield, USA",desktop,Very Good Rating|5 Star|4 Star|Hotel|Motel|Res...,NaN,NaN
130,03P4VFKK12UO,325fafb5fa450,1541107366,8,filter selection,4 Star,US,"Bakersfield, USA",desktop,Very Good Rating|5 Star|4 Star|Hotel|Motel|Res...,NaN,NaN
131,03P4VFKK12UO,325fafb5fa450,1541107366,9,filter selection,5 Star,US,"Bakersfield, USA",desktop,Very Good Rating|5 Star|4 Star|Hotel|Motel|Res...,NaN,NaN
136,03P4VFKK12UO,325fafb5fa450,1541107368,14,filter selection,3 Star,US,"Bakersfield, USA",desktop,Very Good Rating|5 Star|4 Star|Hotel|Motel|Res...,NaN,NaN
139,03P4VFKK12UO,325fafb5fa450,1541107435,17,interaction item image,65685,US,"Bakersfield, USA",desktop,NaN,NaN,NaN
176,03P4VFKK12UO,325fafb5fa450,1541107500,54,clickout item,65685,US,"Bakersfield, USA",desktop,Very Good Rating|5 Star|4 Star|Hotel|Motel|Res...,1306936|56482|2842358|6881276|65685|63259|6539...,178|104|110|94|57|96|46|61|48|35|50|38|59|44|5...
...,...,...,...,...,...,...,...,...,...,...,...,...
15932358,XUVMOYVY9HRV,37ea06bb88388,1541473607,32,clickout item,10152482,AU,"Savusavu, Fiji",tablet,NaN,382911|3133582|5434250|10152482|1324248|382657...,435|1059|78|64|85|67|262|62|67|1172|920|122|81|72
15932359,XUVMOYVY9HRV,37ea06bb88388,1541473794,33,clickout item,1324248,AU,"Savusavu, Fiji",tablet,NaN,382911|3133582|5434250|10152482|1324248|382657...,435|1059|78|64|85|67|262|62|67|1172|920|122|81|72
15932360,XUVMOYVY9HRV,37ea06bb88388,1541473877,34,clickout item,3826574,AU,"Savusavu, Fiji",tablet,NaN,382911|3133582|5434250|10152482|1324248|382657...,435|1059|78|64|85|67|262|62|67|1172|920|122|81|72
15932362,XUVMOYVY9HRV,37ea06bb88388,1541474183,36,clickout item,3770124,AU,"Savusavu, Fiji",tablet,NaN,382911|3133582|5434250|10152482|1324248|382657...,435|1059|78|64|85|67|262|62|67|1172|920|122|81|72
15932372,XW75HD7O1OY8,78d109891ce82,1541525429,5,interaction item deals,675196,GR,"Krakow, Poland",desktop,NaN,NaN,NaN
15932380,XW75HD7O1OY8,78d109891ce82,1541526222,13,interaction item deals,5882886,GR,"Krakow, Poland",desktop,NaN,NaN,NaN
15932393,XW75HD7O1OY8,78d109891ce82,1541526748,26,interaction item rating,6704022,GR,"Krakow, Poland",desktop,NaN,NaN,NaN
15932394,XW75HD7O1OY8,78d109891ce82,1541526767,27,clickout item,5762850,GR,"Krakow, Poland",desktop,NaN,7568226|3407130|6704022|927193|3928554|9182862...,56|44|52|74|93|93|50|62|55|69|56|86|57|89|82|7...
15932397,XW75HD7O1OY8,78d109891ce82,1541527225,30,interaction item image,4076774,GR,"Krakow, Poland",desktop,NaN,NaN,NaN
15932402,XW75HD7O1OY8,78d109891ce82,1541527236,35,clickout item,4076774,GR,"Krakow, Poland",desktop,NaN,7857324|107577|148861|4493966|152787|152786|81...,100|69|77|85|63|87|68|98|64|99|67|74|61|50|43|...
15932403,XW75HD7O1OY8,78d109891ce82,1541527337,36,interaction item deals,4076774,GR,"Krakow, Poland",desktop,NaN,NaN,NaN
15932423,Y0NMJ7FLTSYT,0b56b5540121c,1541507927,1,search for poi,Castillo de Xátiva,UK,"Játiva, Spain",desktop,NaN,NaN,NaN
15932548,YA0B26091H3Q,fa252ef7d1032,1541489183,46,interaction item info,2326002,AE,"Dubai, United Arab Emirates",mobile,NaN,NaN,NaN
15932569,YH5BH5INZMHX,068dcaa3b08b4,1541518492,1,clickout item,1160332,UK,"London, United Kingdom",desktop,NaN,12669|1160332|47617|6255610|46875|47412|116036...,51|314|147|143|280|102|701|229|81|62|759|120|6...
15932570,YH5BH5INZMHX,068dcaa3b08b4,1541518648,2,search for item,1160332,UK,"London, United Kingdom",desktop,NaN,NaN,NaN
15932607,YQCVP517L5I3,3d5cf2957a6da,1541529174,1,interaction item rating,4834976,ES,"Formentera, Spain",desktop,NaN,NaN,NaN
15932610,YQCVP517L5I3,3d5cf2957a6da,1541529240,4,interaction item rating,1265311,ES,"Formentera, Spain",desktop,NaN,NaN,NaN
15932612,YQCVP517L5I3,3d5cf2957a6da,1541529363,6,interaction item deals,4834976,ES,"Formentera, Spain",desktop,NaN,NaN,NaN
15932650,YQCVP517L5I3,3d5cf2957a6da,1541529448,44,interaction item image,1265311,ES,"Formentera, Spain",desktop,NaN,NaN,NaN
15932661,YQCVP517L5I3,3d5cf2957a6da,1541529478,55,clickout item,5443562,ES,"Formentera, Spain",desktop,NaN,1265311|4834976|5443562|38940|4821722|3971550|...,46|79|45|83|74|64|57|79|414|414
15932683,YRVVFF4XMK2Z,f3814f0165e9c,1541511201,1,search for poi,Arenella beach,UK,"Syracuse, Italy",desktop,NaN,NaN,NaN
15932720,Z6W0KZ1LCB8H,a4c049a08e980,1541497380,2,interaction item image,10218812,AU,"Murray Bridge, Australia",mobile,NaN,NaN,NaN
15932722,Z6W0KZ1LCB8H,a4c049a08e980,1541497387,4,clickout item,10218812,AU,"Murray Bridge, Australia",mobile,NaN,1398634|10907042|10218812|10276592|10160808|10...,249|459|93|201|554|477|71
15932723,Z6W0KZ1LCB8H,a4c049a08e980,1541497390,5,interaction item info,10218812,AU,"Murray Bridge, Australia",mobile,NaN,NaN,NaN
15932724,Z6W0KZ1LCB8H,a4c049a08e980,1541497390,6,interaction item deals,10218812,AU,"Murray Bridge, Australia",mobile,NaN,NaN,NaN
15932729,Z6W0KZ1LCB8H,a4c049a08e980,1541497818,11,interaction item deals,1627067,AU,"Adelaide, Australia",mobile,NaN,NaN,NaN
15932746,Z6W0KZ1LCB8H,a4c049a08e980,1541498612,28,interaction item image,4201464,AU,"Adelaide, Australia",mobile,NaN,NaN,NaN
15932749,Z6W0KZ1LCB8H,a4c049a08e980,1541498622,31,interaction item info,4201464,AU,"Adelaide, Australia",mobile,NaN,NaN,NaN
15932806,ZDPW9IS37UBJ,8b6e093507d36,1541480587,3,clickout item,2627868,IN,"Port Blair, India",desktop,NaN,3045966|2627868|1029890|5464176|1052052|434922...,61|20|57|26|61|17|90|18|62|31|61|53|10|39|86|3...
15932811,ZE8M21HENJ91,f0cceac1f5925,1541516869,1,clickout item,1771251,PL,"Radziejowice, Poland",mobile,NaN,2199498|2258162|1826617|1771183|1771251|131913...,25|60|97|58|37|42|35|31|42|32|37|38|49|60|42|3...

In [5]:
imp = pd.DataFrame(session_t.impressions)
imp = imp[~imp["impressions"].isnull()]
imp = imp.impressions
imp_sp =imp.str.split('|')
imp_sp = imp_sp.apply(lambda x : pd.Series(x))

In [6]:
imp_sin = imp_sp.stack().to_frame('imp_sin')
imp_sin.T

        13                                                                    \
              0        1        2        3        4       5      6        7
imp_sin  3400638  1253714  3367857  5100540  1088584  666916  54833  2922310

                           ...    15932811                             \
              8       9    ...          15       16       17       18
imp_sin  9711560  109038   ...     2860970  5168042  1623105  2894022


              19       20       21       22       23       24
imp_sin  5577440  2599282  2404490  3076456  1623211  8948588

[1 rows x 6305525 columns]

In [7]:
pri = pd.DataFrame(session_t.prices)
pri = pri[~pri["prices"].isnull()]
pri = pri.prices
pri_sp = pri.str.split('|')
pri_sp = pri_sp.apply(lambda x : pd.Series(x))
pri_sp

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
13,95,66,501,112,95,100,101,72,82,56,...,162,73,143,188,118,77,131,143,49,165
15,162,25,150,143,101,49,118,131,18,100,...,36,66,188,124,138,94,137,180,112,118
115,64,54,36,121,76,81,92,40,73,52,...,111,21,122,55,104,56,64,40,29,44
121,104,92,100,103,102,104,72,85,81,75,...,103,105,99,106,99,98,96,96,105,99
176,178,104,110,94,57,96,46,61,48,35,...,56,55,45,146,41,44,44,39,38,126
177,178,104,110,94,57,96,46,61,48,35,...,56,55,45,146,41,44,44,39,38,126
180,51,43,69,49,62,50,55,42,87,46,...,351,22,154,116,89,55,270,192,92,26
181,54,39,55,51,41,94,24,38,59,24,...,51,50,129,96,118,86,125,51,50,117
184,36,45,99,48,49,50,49,56,40,63,...,48,76,62,58,43,53,126,65,42,45
188,158,166,145,145,62,129,100,128,139,95,...,110,145,130,125,125,104,99,90,95,75
191,158,166,145,145,62,129,100,128,139,95,...,110,145,130,125,125,104,99,90,95,75
196,280,169,82,138,60,270,100,204,103,37,...,149,63,144,84,84,139,78,85,90,72
230,17,37,29,35,97,23,31,62,31,82,...,31,69,29,46,177,63,62,18,47,29
236,268,160,300,141,187,278,168,447,123,291,...,304,224,185,116,174,106,115,146,237,233
237,117,104,82,130,204,140,147,75,104,149,...,131,43,170,98,83,146,80,81,108,359
240,225,23,58,53,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
260,82,65,246,126,75,1004,35,75,64,175,...,98,71,86,80,83,78,48,56,71,41
264,11,26,24,20,20,22,19,10,22,26,...,15,15,16,40,23,22,20,21,35,43
279,124,176,99,220,191,127,85,54,83,268,...,154,135,85,74,115,152,131,83,108,79
285,249,122,110,81,81,42,74,109,62,91,...,67,59,101,223,110,108,135,87,189,72
287,59,52,66,219,104,95,85,69,125,176,...,30,102,16,129,83,85,100,61,139,143
293,85,87,122,74,79,123,101,83,95,219,...,176,249,135,268,99,190,145,110,93,135
296,104,57,79,91,76,80,68,63,91,63,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
297,113,144,82,47,49,98,50,16,72,26,...,46,53,26,28,42,39,54,33,34,16
300,141,69,82,107,122,54,53,60,39,58,...,31,58,15,28,24,22,50,20,35,51
303,141,69,82,107,122,54,53,60,39,58,...,31,58,15,28,24,22,50,20,35,51
306,141,69,82,107,122,54,53,60,39,58,...,31,58,15,28,24,22,50,20,35,51
328,106,82,88,93,92,149,81,48,84,62,...,73,50,54,34,28,240,53,35,173,72
445,44,87,30,62,73,59,85,43,68,31,...,116,29,79,38,42,28,47,28,50,67
466,44,87,30,62,73,59,85,43,68,31,...,116,29,79,38,42,28,47,28,50,67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15929334,65,98,69,102,82,120,123,89,50,45,...,82,61,54,79,60,66,85,73,133,60
15929432,50,646,22,88,106,36,42,123,92,69,...,69,10,282,69,82,109,12,17,24,21
15929442,50,646,22,88,106,36,42,123,92,69,...,69,10,282,69,82,109,12,17,24,21
15929443,50,646,22,88,106,36,42,123,92,69,...,69,10,282,69,82,109,12,17,24,21
15929473,121,62,75,49,174,273,290,92,99,37,...,76,286,99,99,92,46,107,91,259,286
15929705,9,12,17,21,21,22,28,31,41,44,...,78,80,84,88,88,88,105,105,106,107
15929806,56,260,197,135,154,75,63,78,138,167,...,37,117,44,40,77,153,84,98,122,263
15929919,342,211,125,367,250,135,434,108,309,290,...,83,113,117,177,725,61,154,158,138,83
15930227,102,67,97,45,80,113,79,72,92,80,...,97,80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15930228,102,67,97,45,80,113,79,72,92,80,...,97,80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15930241,81,62,55,86,114,95,50,62,80,85,...,70,62,88,117,68,55,58,65,85,389
15930700,42,40,36,37,31,139,164,89,91,156,...,48,61,55,64,80,96,86,127,75,NaN
15931576,184,74,96,54,70,89,193,132,96,91,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15931594,106,116,90,48,40,51,66,70,72,55,...,76,58,77,112,NaN,NaN,NaN,NaN,NaN,NaN
15931755,18,99,155,73,111,48,147,31,22,35,...,47,22,80,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15931838,24,32,20,38,36,31,66,18,52,61,...,47,64,22,281,44,100,28,13,42,45
15932169,122,120,110,61,86,188,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15932204,23,9,7,8,14,23,35,30,9,8,...,6,22,43,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15932318,25,360,11,120,78,22,34,48,87,45,...,40,30,89,28,24,50,26,28,21,28
15932358,435,1059,78,64,85,67,262,62,67,1172,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15932359,435,1059,78,64,85,67,262,62,67,1172,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15932360,435,1059,78,64,85,67,262,62,67,1172,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15932362,435,1059,78,64,85,67,262,62,67,1172,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15932394,56,44,52,74,93,93,50,62,55,69,...,70,75,71,88,73,99,60,83,72,87
15932402,100,69,77,85,63,87,68,98,64,99,...,61,50,52,67,62,77,65,76,92,44
15932569,51,314,147,143,280,102,701,229,81,62,...,90,466,94,215,391,447,366,531,90,300
15932661,46,79,45,83,74,64,57,79,414,414,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15932722,249,459,93,201,554,477,71,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15932806,61,20,57,26,61,17,90,18,62,31,...,38,26,50,51,63,77,24,33,32,18
15932811,25,60,97,58,37,42,35,31,42,32,...,37,30,35,37,32,35,68,45,42,46

In [8]:
pri_sin = pri_sp.stack().to_frame('pri_sin')
pri_sin

            pri_sin
13       0       95
         1       66
         2      501
         3      112
         4       95
         5      100
         6      101
         7       72
         8       82
         9       56
         10      56
         11     143
         12      70
         13      25
         14      71
         15     162
         16      73
         17     143
         18     188
         19     118
         20      77
         21     131
         22     143
         23      49
         24     165
15       0      162
         1       25
         2      150
         3      143
         4      101
...             ...
15932806 20      77
         21      24
         22      33
         23      32
         24      18
15932811 0       25
         1       60
         2       97
         3       58
         4       37
         5       42
         6       35
         7       31
         8       42
         9       32
         10      37
         11      38
         12      49
         13      60
         14      42
         15      37
         16      30
         17      35
         18      37
         19      32
         20      35
         21      68
         22      45
         23      42
         24      46

[6305525 rows x 1 columns]

In [9]:
imp_pri = pd.concat([imp_sin, pri_sin], axis = 1)
imp_pri

              imp_sin pri_sin
13       0    3400638      95
         1    1253714      66
         2    3367857     501
         3    5100540     112
         4    1088584      95
         5     666916     100
         6      54833     101
         7    2922310      72
         8    9711560      82
         9     109038      56
         10    666856      56
         11  10077318     143
         12   1431482      70
         13    129343      25
         14   6339822      71
         15   6806806     162
         16   1041528      73
         17    109013     143
         18   3909420     188
         19     55088     118
         20   3095758      77
         21    109018     131
         22     54885     143
         23   1257342      49
         24   2595006     165
15       0      55109     162
         1     129343      25
         2      54824     150
         3    2297972     143
         4     109014     101
...               ...     ...
15932806 20   9397904      77
         21   6059326      24
         22   2664370      33
         23   4855538      32
         24   5870994      18
15932811 0    2199498      25
         1    2258162      60
         2    1826617      97
         3    1771183      58
         4    1771251      37
         5    1319136      42
         6    8220208      35
         7    2680694      31
         8    4083978      42
         9    1665669      32
         10   2424957      37
         11   1623163      38
         12   7933642      49
         13   1843121      60
         14   1335808      42
         15   2860970      37
         16   5168042      30
         17   1623105      35
         18   2894022      37
         19   5577440      32
         20   2599282      35
         21   2404490      68
         22   3076456      45
         23   1623211      42
         24   8948588      46

[6305525 rows x 2 columns]

In [10]:
imp_pri.to_csv(path_or_buf = os.path.abspath('impression_price.csv'))

In [11]:
pos = session_t[session_t["action_type"] == "clickout item"]
pos = pos[["user_id", "step", "action_type", "reference"]]
pos

               user_id  step    action_type reference
13        00RL8Z82B2Z1    14  clickout item    109038
15        00RL8Z82B2Z1    16  clickout item   1257342
115       02SRUT1NQYH1    35  clickout item   2795374
121       03K8AXBL4BX2     6  clickout item   1032816
176       03P4VFKK12UO    54  clickout item     65685
177       03P4VFKK12UO    55  clickout item   1320460
180       0473FZ8UNXRS     3  clickout item   3143258
181       066TUPQWUEV5     1  clickout item   2552514
184       06S61EKCW1JY     1  clickout item    110591
188       06SZHKMYOOI8     4  clickout item   2557176
191       06SZHKMYOOI8     7  clickout item    138930
196       098CQXLJZ868     1  clickout item    129881
230       09L0Y03JYTAC    34  clickout item      8561
236       0FXZGX34RQMS     6  clickout item   2529658
237       0FZ7FKT6CB3D     1  clickout item    921237
240       0IVOT7X0FJWE     2  clickout item   9167996
260       0K009FGORI30     5  clickout item    104499
264       0KCQVHPEIWT0     3  clickout item   4138580
279       0L2TX0JNYVQ6     2  clickout item  10091602
285       0L2TX0JNYVQ6     8  clickout item   1394008
287       0L2TX0JNYVQ6    10  clickout item   5109850
293       0L2TX0JNYVQ6    16  clickout item   6893402
296       0LEN9Z40SUSJ     3  clickout item   3191226
297       0LPWXP7ZIW88     1  clickout item   9387652
300       0LPWXP7ZIW88     4  clickout item   2564964
303       0LPWXP7ZIW88     7  clickout item   2896408
306       0LPWXP7ZIW88    10  clickout item   3484132
328       0LPWXP7ZIW88    32  clickout item   6696574
445       0NA8E4AD2VY7    91  clickout item   1091180
466       0NA8E4AD2VY7   112  clickout item   3404929
...                ...   ...            ...       ...
15929334  O6PGH6P380V0     6  clickout item   2333086
15929432  OKBRK841UAEA     9  clickout item   2077410
15929442  OKBRK841UAEA    19  clickout item   3805278
15929443  OKBRK841UAEA    20  clickout item   5004014
15929473  ON44RYNL8Z5F     1  clickout item   6458836
15929705  PBOJ1LR1TW4V    12  clickout item   9422578
15929806  Q7RX8KTMQO85     6  clickout item   1947487
15929919  QBHZM85H2RW4     2  clickout item   1147284
15930227  ROG19VVO2H2U     2  clickout item   1952457
15930228  ROG19VVO2H2U     3  clickout item   3999570
15930241  RSPH5EHVMMNV     3  clickout item   1775955
15930700  SKW3GUI2E91I     4  clickout item   2432094
15931576  UZJSXE1N3YQX     1  clickout item   8740008
15931594  V663LY5OUETP    13  clickout item    955427
15931755  W4EHRPEPLUXA     2  clickout item   9023072
15931838  W8L1MVW5E5RZ     1  clickout item   1363806
15932169  WY9XYHIKQ6CG     9  clickout item   1370793
15932204  XDS4KAMBY24Y     1  clickout item   4899198
15932318  XPD9WIHUYF96     2  clickout item   6824218
15932358  XUVMOYVY9HRV    32  clickout item  10152482
15932359  XUVMOYVY9HRV    33  clickout item   1324248
15932360  XUVMOYVY9HRV    34  clickout item   3826574
15932362  XUVMOYVY9HRV    36  clickout item   3770124
15932394  XW75HD7O1OY8    27  clickout item   5762850
15932402  XW75HD7O1OY8    35  clickout item   4076774
15932569  YH5BH5INZMHX     1  clickout item   1160332
15932661  YQCVP517L5I3    55  clickout item   5443562
15932722  Z6W0KZ1LCB8H     4  clickout item  10218812
15932806  ZDPW9IS37UBJ     3  clickout item   2627868
15932811  ZE8M21HENJ91     1  clickout item   1771251

[289506 rows x 4 columns]

In [12]:
pos_last = pos.drop_duplicates(["user_id","action_type"], "last")
pos_last

               user_id  step    action_type reference
15        00RL8Z82B2Z1    16  clickout item   1257342
115       02SRUT1NQYH1    35  clickout item   2795374
177       03P4VFKK12UO    55  clickout item   1320460
180       0473FZ8UNXRS     3  clickout item   3143258
181       066TUPQWUEV5     1  clickout item   2552514
184       06S61EKCW1JY     1  clickout item    110591
191       06SZHKMYOOI8     7  clickout item    138930
196       098CQXLJZ868     1  clickout item    129881
230       09L0Y03JYTAC    34  clickout item      8561
236       0FXZGX34RQMS     6  clickout item   2529658
237       0FZ7FKT6CB3D     1  clickout item    921237
240       0IVOT7X0FJWE     2  clickout item   9167996
260       0K009FGORI30     5  clickout item    104499
264       0KCQVHPEIWT0     3  clickout item   4138580
293       0L2TX0JNYVQ6    16  clickout item   6893402
296       0LEN9Z40SUSJ     3  clickout item   3191226
466       0NA8E4AD2VY7   112  clickout item   3404929
468       0NN8D1GWBW1F     1  clickout item   9164598
490       0O1CTEP95YKQ    22  clickout item      8602
495       0P3WZY097PQI     5  clickout item   2793224
542       0Q3605EUBZG3    47  clickout item   9112068
550       0RH6DTZGIKY8     8  clickout item   1236209
564       0S2J3RLMF1LO     6  clickout item    327111
593       0SO132S6MH3O    24  clickout item   9590036
599       0SVH5QYX372P     6  clickout item   3753160
604       0T819ODEIRA4     5  clickout item   5170834
607       0VNR91BTRLCP     1  clickout item    107674
608       0VOL2T63B8FS     1  clickout item   6337814
627       0X3OMZZH37ZS     8  clickout item    434856
628       0YBM60V6E5V6     1  clickout item     42349
...                ...   ...            ...       ...
15928820  MKXLJ5LI2YEW    10  clickout item   5112182
15928876  N2JDLL7FU4DX     4  clickout item  10151456
15928881  N3287DG463JG     1  clickout item    124628
15928884  N3ID0M4TYCH6     3  clickout item    451961
15928982  N4N4R3MGIVS2     5  clickout item   3916108
15929034  N9FKHZLM3KDJ     4  clickout item   4118916
15929036  NA6NCKP12L2U     1  clickout item  10923096
15929334  O6PGH6P380V0     6  clickout item   2333086
15929443  OKBRK841UAEA    20  clickout item   5004014
15929473  ON44RYNL8Z5F     1  clickout item   6458836
15929705  PBOJ1LR1TW4V    12  clickout item   9422578
15929806  Q7RX8KTMQO85     6  clickout item   1947487
15929919  QBHZM85H2RW4     2  clickout item   1147284
15930228  ROG19VVO2H2U     3  clickout item   3999570
15930241  RSPH5EHVMMNV     3  clickout item   1775955
15930700  SKW3GUI2E91I     4  clickout item   2432094
15931576  UZJSXE1N3YQX     1  clickout item   8740008
15931594  V663LY5OUETP    13  clickout item    955427
15931755  W4EHRPEPLUXA     2  clickout item   9023072
15931838  W8L1MVW5E5RZ     1  clickout item   1363806
15932169  WY9XYHIKQ6CG     9  clickout item   1370793
15932204  XDS4KAMBY24Y     1  clickout item   4899198
15932318  XPD9WIHUYF96     2  clickout item   6824218
15932362  XUVMOYVY9HRV    36  clickout item   3770124
15932402  XW75HD7O1OY8    35  clickout item   4076774
15932569  YH5BH5INZMHX     1  clickout item   1160332
15932661  YQCVP517L5I3    55  clickout item   5443562
15932722  Z6W0KZ1LCB8H     4  clickout item  10218812
15932806  ZDPW9IS37UBJ     3  clickout item   2627868
15932811  ZE8M21HENJ91     1  clickout item   1771251

[207170 rows x 4 columns]

In [17]:
pos_ref = pos_last.reference
# pos_ref = pd.DataFrame(pos_ref)
# pos_ref.to_csv(path_or_buf = os.path.abspath('positive_reference.csv'))
pos_ref

15           1257342
115          2795374
177          1320460
180          3143258
181          2552514
184           110591
191           138930
196           129881
230             8561
236          2529658
237           921237
240          9167996
260           104499
264          4138580
293          6893402
296          3191226
466          3404929
468          9164598
490             8602
495          2793224
542          9112068
550          1236209
564           327111
593          9590036
599          3753160
604          5170834
607           107674
608          6337814
627           434856
628            42349
              ...
15928820     5112182
15928876    10151456
15928881      124628
15928884      451961
15928982     3916108
15929034     4118916
15929036    10923096
15929334     2333086
15929443     5004014
15929473     6458836
15929705     9422578
15929806     1947487
15929919     1147284
15930228     3999570
15930241     1775955
15930700     2432094
15931576     8740008
15931594      955427
15931755     9023072
15931838     1363806
15932169     1370793
15932204     4899198
15932318     6824218
15932362     3770124
15932402     4076774
15932569     1160332
15932661     5443562
15932722    10218812
15932806     2627868
15932811     1771251
Name: reference, Length: 207170, dtype: object

In [19]:
# def pos(data):
#     if data in pos_ref:
#         return 1
#     else:
#         return 0

In [14]:
# filter=imp_pri["imp_sin"].isin(pos_ref)

In [22]:
# imp_pri["positive"] = imp_pri.imp_sin.isin(pos_ref)

In [27]:
ref_list = pos_ref.tolist()

In [29]:
pattern = '|'.join(ref_list)

In [31]:
imp_pri["positive"] = imp_pri.imp_sin.str.contains(pattern)

In [33]:
imp_pri.head()

      imp_sin pri_sin  positive
13 0  3400638      95      True
   1  1253714      66      True
   2  3367857     501      True
   3  5100540     112      True
   4  1088584      95     False

In [23]:
pos(1771251)

1

In [32]:
imp_pri.to_csv(path_or_buf = os.path.abspath('imp_pri.csv'))

In [45]:
imp_pri_ = pd.read_csv("imp_pri.csv")

In [46]:
imp_pri_

         Unnamed: 0  Unnamed: 1   item_id  price  positive
0             35375          12      5001     82      True
1             36246          21      5001     84      True
2            103488           5      5001     94      True
3            103490           5      5001     94      True
4            103492           5      5001     94      True
5            163436           7      5001     94      True
6            435705           6      5001     82      True
7            435706           6      5001     82      True
8            720915           5      5001    105      True
9            720918           5      5001    105      True
10           103488          21      5002    105     False
11           103490          21      5002    105     False
12           103492          21      5002    105     False
13           103542          19      5002    105     False
14           435705           5      5002     72     False
15           435706           5      5002     72     False
16           720915          17      5002     75     False
17           720918          17      5002     75     False
18            35375          11      5003    106     False
19            36246           9      5003    106     False
20           103488           1      5003    106     False
21           103490           1      5003    106     False
22           103492           1      5003    106     False
23           103542           3      5003    106     False
24           163436          12      5003    112     False
25           435705           0      5003    106     False
26           435706           0      5003    106     False
27           720915           0      5003    119     False
28           720918           0      5003    119     False
29           103488          19      5004    139      True
...             ...         ...       ...    ...       ...
1048545      488880           0  11259944     13      True
1048546      161508           8  11260024    428     False
1048547      556796          22  11260166    175      True
1048548      556797          22  11260166    175      True
1048549      159597          24  11261214    120      True
1048550      314807          23  11261432   1303      True
1048551      712300          17  11262114     32      True
1048552      305581          15  11263332     55      True
1048553      305582           7  11263332     55      True
1048554      303428          13  11263724     32      True
1048555      305582           8  11264984     18      True
1048556      312648          21  11265060    127      True
1048557      207906          17  11265326    124     False
1048558      145974          19  11265454     43      True
1048559      384260          24  11265454     43      True
1048560      487073           4  11265478    121      True
1048561      452680          10  11265662    550      True
1048562      212722          11  11266190    351      True
1048563      226638          22  11266460     18      True
1048564      226639          22  11266460     18      True
1048565      221591          21  11266594    165      True
1048566      452680          12  11267426    550      True
1048567       58693          11  11267482     45      True
1048568      124849          21  11267574    125      True
1048569      217927          23  11268206    273      True
1048570      130572           8  11268332    245      True
1048571      304775           9  11268332    151      True
1048572      154535          16  11274270     60      True
1048573      247275           9  11274320     50      True
1048574      567526          23  11274476     21      True

[1048575 rows x 5 columns]

In [36]:
property_onehot_sum = pd.read_csv('property_onehot_sum.csv')

In [74]:
train_i = pd.merge(imp_pri_, property_onehot_sum, on="item_id")

In [75]:
train_i = train_i.drop(["Unnamed: 0", "Unnamed: 1"], axis = 1)

In [76]:
# train_i["positive"] = train_i["positive"].apply(lambda x : '1' if x == 'True' else '0')
train_i.positive = train_i.positive.astype(int)

In [77]:
train_i

,item_id,price,positive,1 Star,2 Star,3 Star,4 Star,5 Star,Accessible Hotel,Accessible Parking,...,Terrace (Hotel),Theme Hotel,Towels,Very Good Rating,Volleyball,Washing Machine,Water Slide,Wheelchair Accessible,WiFi (Public Areas),WiFi (Rooms)
0,5001,82,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,1
1,5001,84,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,1
2,5001,94,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,1
3,5001,94,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,1
4,5001,94,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,1
5,5001,94,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,1
6,5001,82,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,1
7,5001,82,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,1
8,5001,105,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,1
9,5001,105,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,1
10,5002,105,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,1
11,5002,105,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,1
12,5002,105,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,1
13,5002,105,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,1
14,5002,72,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,1
15,5002,72,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,1
16,5002,75,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,1
17,5002,75,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,1
18,5003,106,0,0,0,0,1,0,1,0,...,1,0,1,1,0,0,0,1,1,1
19,5003,106,0,0,0,0,1,0,1,0,...,1,0,1,1,0,0,0,1,1,1
20,5003,106,0,0,0,0,1,0,1,0,...,1,0,1,1,0,0,0,1,1,1
21,5003,106,0,0,0,0,1,0,1,0,...,1,0,1,1,0,0,0,1,1,1
22,5003,106,0,0,0,0,1,0,1,0,...,1,0,1,1,0,0,0,1,1,1
23,5003,106,0,0,0,0,1,0,1,0,...,1,0,1,1,0,0,0,1,1,1
24,5003,112,0,0,0,0,1,0,1,0,...,1,0,1,1,0,0,0,1,1,1
25,5003,106,0,0,0,0,1,0,1,0,...,1,0,1,1,0,0,0,1,1,1
26,5003,106,0,0,0,0,1,0,1,0,...,1,0,1,1,0,0,0,1,1,1
27,5003,119,0,0,0,0,1,0,1,0,...,1,0,1,1,0,0,0,1,1,1
28,5003,119,0,0,0,0,1,0,1,0,...,1,0,1,1,0,0,0,1,1,1
29,5004,139,1,0,0,0,1,0,0,0,...,1,0,0,1,0,0,0,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048113,11259944,13,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1048114,11260024,428,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1048115,11260166,175,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1048116,11260166,175,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1048117,11261214,120,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1048118,11261432,1303,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1048119,11262114,32,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1048120,11263332,55,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1048121,11263332,55,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1048122,11263724,32,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1048123,11264984,18,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1048124,11265060,127,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1048125,11265326,124,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1048126,11265454,43,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1048127,11265454,43,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1048128,11265478,121,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1048129,11265662,550,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1048130,11266190,351,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1048131,11266460,18,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1048132,11266460,18,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1048133,11266594,165,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1048134,11267426,550,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1048135,11267482,45,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1048136,11267574,125,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1048137,11268206,273,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1048138,11268332,245,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1048139,11268332,151,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1048140,11274270,60,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1048141,11274320,50,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1048142,11274476,21,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [78]:
train_i.to_csv(path_or_buf = os.path.abspath("train_i.csv"))

In [79]:
train_i.price.nlargest(1)

759195    9996
Name: price, dtype: int64

In [83]:
import xlearn as xl
# def test():
#     fm_model = xl.create_fm()

XLearnLibraryNotFound: Cannot find xlearn Library in the candidate path