In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
train = pd.read_csv("train.csv")

In [7]:
train[0:10]

,user_id,session_id,timestamp,step,action_type,reference,platform,city,device,current_filters,impressions,prices
0,00RL8Z82B2Z1,aff3928535f48,1541037460,1,search for poi,Newtown,AU,"Sydney, Australia",mobile,NaN,NaN,NaN
1,00RL8Z82B2Z1,aff3928535f48,1541037522,2,interaction item image,666856,AU,"Sydney, Australia",mobile,NaN,NaN,NaN
2,00RL8Z82B2Z1,aff3928535f48,1541037522,3,interaction item image,666856,AU,"Sydney, Australia",mobile,NaN,NaN,NaN
3,00RL8Z82B2Z1,aff3928535f48,1541037532,4,interaction item image,666856,AU,"Sydney, Australia",mobile,NaN,NaN,NaN
4,00RL8Z82B2Z1,aff3928535f48,1541037532,5,interaction item image,109038,AU,"Sydney, Australia",mobile,NaN,NaN,NaN
5,00RL8Z82B2Z1,aff3928535f48,1541037532,6,interaction item image,666856,AU,"Sydney, Australia",mobile,NaN,NaN,NaN
6,00RL8Z82B2Z1,aff3928535f48,1541037532,7,interaction item image,109038,AU,"Sydney, Australia",mobile,NaN,NaN,NaN
7,00RL8Z82B2Z1,aff3928535f48,1541037532,8,interaction item image,666856,AU,"Sydney, Australia",mobile,NaN,NaN,NaN
8,00RL8Z82B2Z1,aff3928535f48,1541037542,9,interaction item image,109038,AU,"Sydney, Australia",mobile,NaN,NaN,NaN
9,00RL8Z82B2Z1,aff3928535f48,1541037542,10,interaction item image,109038,AU,"Sydney, Australia",mobile,NaN,NaN,NaN

In [11]:
session_t = dict(list(train.groupby(train.session_id)))

In [3]:
session_t = train.drop_duplicates(["action_type","reference"], "first")

In [20]:
session_t

,user_id,session_id,timestamp,step,action_type,reference,platform,city,device,current_filters,impressions,prices
0,00RL8Z82B2Z1,aff3928535f48,1541037460,1,search for poi,Newtown,AU,"Sydney, Australia",mobile,NaN,NaN,NaN
1,00RL8Z82B2Z1,aff3928535f48,1541037522,2,interaction item image,666856,AU,"Sydney, Australia",mobile,NaN,NaN,NaN
4,00RL8Z82B2Z1,aff3928535f48,1541037532,5,interaction item image,109038,AU,"Sydney, Australia",mobile,NaN,NaN,NaN
13,00RL8Z82B2Z1,aff3928535f48,1541037543,14,clickout item,109038,AU,"Sydney, Australia",mobile,NaN,3400638|1253714|3367857|5100540|1088584|666916...,95|66|501|112|95|100|101|72|82|56|56|143|70|25...
14,00RL8Z82B2Z1,aff3928535f48,1541038469,15,search for poi,Surry Hills,AU,"Sydney, Australia",mobile,NaN,NaN,NaN
15,00RL8Z82B2Z1,aff3928535f48,1541038485,16,clickout item,1257342,AU,"Sydney, Australia",mobile,NaN,55109|129343|54824|2297972|109014|1257342|1031...,162|25|150|143|101|49|118|131|18|100|101|143|5...
16,02HGRBA06ODU,fa3a53156ae5c,1541030832,1,interaction item info,3377332,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN
17,02HGRBA06ODU,fa3a53156ae5c,1541030843,2,interaction item image,3377332,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN
20,02HGRBA06ODU,fa3a53156ae5c,1541030867,5,interaction item info,3066244,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN
21,02HGRBA06ODU,fa3a53156ae5c,1541030877,6,interaction item image,3066244,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN
62,02HGRBA06ODU,fa3a53156ae5c,1541031044,47,interaction item deals,3066244,BR,"Ubatuba, Brazil",mobile,NaN,NaN,NaN
81,02SRUT1NQYH1,3599a6f709eab,1541063730,1,interaction item image,2795374,FI,"Krakow, Poland",mobile,NaN,NaN,NaN
114,02SRUT1NQYH1,3599a6f709eab,1541063863,34,interaction item info,2795374,FI,"Krakow, Poland",mobile,NaN,NaN,NaN
115,02SRUT1NQYH1,3599a6f709eab,1541063864,35,clickout item,2795374,FI,"Krakow, Poland",mobile,NaN,2795374|5582964|1088390|2781070|1258068|127196...,64|54|36|121|76|81|92|40|73|52|98|104|56|414|6...
116,03K8AXBL4BX2,ec139e10b9238,1541100038,1,search for destination,"London, United Kingdom",UK,"London, United Kingdom",desktop,NaN,NaN,NaN
117,03K8AXBL4BX2,ec139e10b9238,1541100132,2,search for poi,Covent Garden,UK,"London, United Kingdom",desktop,NaN,NaN,NaN
118,03K8AXBL4BX2,ec139e10b9238,1541100193,3,search for poi,Oxford Street,UK,"London, United Kingdom",desktop,NaN,NaN,NaN
119,03K8AXBL4BX2,ec139e10b9238,1541100314,4,interaction item image,1032816,UK,"London, United Kingdom",desktop,NaN,NaN,NaN
121,03K8AXBL4BX2,ec139e10b9238,1541100322,6,clickout item,1032816,UK,"London, United Kingdom",desktop,NaN,12693|46363|81657|18448|47687|152913|18417|927...,104|92|100|103|102|104|72|85|81|75|107|86|98|8...
123,03P4VFKK12UO,325fafb5fa450,1541107285,1,search for destination,"Bakersfield, USA",US,"Bakersfield, USA",desktop,NaN,NaN,NaN
125,03P4VFKK12UO,325fafb5fa450,1541107336,3,filter selection,Very Good Rating,US,"Bakersfield, USA",desktop,Very Good Rating,NaN,NaN
126,03P4VFKK12UO,325fafb5fa450,1541107366,4,filter selection,Hostal (ES),US,"Bakersfield, USA",desktop,Very Good Rating|5 Star|4 Star|Hotel|Motel|Res...,NaN,NaN
127,03P4VFKK12UO,325fafb5fa450,1541107366,5,filter selection,Hotel,US,"Bakersfield, USA",desktop,Very Good Rating|5 Star|4 Star|Hotel|Motel|Res...,NaN,NaN
128,03P4VFKK12UO,325fafb5fa450,1541107366,6,filter selection,Motel,US,"Bakersfield, USA",desktop,Very Good Rating|5 Star|4 Star|Hotel|Motel|Res...,NaN,NaN
129,03P4VFKK12UO,325fafb5fa450,1541107366,7,filter selection,Resort,US,"Bakersfield, USA",desktop,Very Good Rating|5 Star|4 Star|Hotel|Motel|Res...,NaN,NaN
130,03P4VFKK12UO,325fafb5fa450,1541107366,8,filter selection,4 Star,US,"Bakersfield, USA",desktop,Very Good Rating|5 Star|4 Star|Hotel|Motel|Res...,NaN,NaN
131,03P4VFKK12UO,325fafb5fa450,1541107366,9,filter selection,5 Star,US,"Bakersfield, USA",desktop,Very Good Rating|5 Star|4 Star|Hotel|Motel|Res...,NaN,NaN
136,03P4VFKK12UO,325fafb5fa450,1541107368,14,filter selection,3 Star,US,"Bakersfield, USA",desktop,Very Good Rating|5 Star|4 Star|Hotel|Motel|Res...,NaN,NaN
139,03P4VFKK12UO,325fafb5fa450,1541107435,17,interaction item image,65685,US,"Bakersfield, USA",desktop,NaN,NaN,NaN
176,03P4VFKK12UO,325fafb5fa450,1541107500,54,clickout item,65685,US,"Bakersfield, USA",desktop,Very Good Rating|5 Star|4 Star|Hotel|Motel|Res...,1306936|56482|2842358|6881276|65685|63259|6539...,178|104|110|94|57|96|46|61|48|35|50|38|59|44|5...
...,...,...,...,...,...,...,...,...,...,...,...,...
15932358,XUVMOYVY9HRV,37ea06bb88388,1541473607,32,clickout item,10152482,AU,"Savusavu, Fiji",tablet,NaN,382911|3133582|5434250|10152482|1324248|382657...,435|1059|78|64|85|67|262|62|67|1172|920|122|81|72
15932359,XUVMOYVY9HRV,37ea06bb88388,1541473794,33,clickout item,1324248,AU,"Savusavu, Fiji",tablet,NaN,382911|3133582|5434250|10152482|1324248|382657...,435|1059|78|64|85|67|262|62|67|1172|920|122|81|72
15932360,XUVMOYVY9HRV,37ea06bb88388,1541473877,34,clickout item,3826574,AU,"Savusavu, Fiji",tablet,NaN,382911|3133582|5434250|10152482|1324248|382657...,435|1059|78|64|85|67|262|62|67|1172|920|122|81|72
15932362,XUVMOYVY9HRV,37ea06bb88388,1541474183,36,clickout item,3770124,AU,"Savusavu, Fiji",tablet,NaN,382911|3133582|5434250|10152482|1324248|382657...,435|1059|78|64|85|67|262|62|67|1172|920|122|81|72
15932372,XW75HD7O1OY8,78d109891ce82,1541525429,5,interaction item deals,675196,GR,"Krakow, Poland",desktop,NaN,NaN,NaN
15932380,XW75HD7O1OY8,78d109891ce82,1541526222,13,interaction item deals,5882886,GR,"Krakow, Poland",desktop,NaN,NaN,NaN
15932393,XW75HD7O1OY8,78d109891ce82,1541526748,26,interaction item rating,6704022,GR,"Krakow, Poland",desktop,NaN,NaN,NaN
15932394,XW75HD7O1OY8,78d109891ce82,1541526767,27,clickout item,5762850,GR,"Krakow, Poland",desktop,NaN,7568226|3407130|6704022|927193|3928554|9182862...,56|44|52|74|93|93|50|62|55|69|56|86|57|89|82|7...
15932397,XW75HD7O1OY8,78d109891ce82,1541527225,30,interaction item image,4076774,GR,"Krakow, Poland",desktop,NaN,NaN,NaN
15932402,XW75HD7O1OY8,78d109891ce82,1541527236,35,clickout item,4076774,GR,"Krakow, Poland",desktop,NaN,7857324|107577|148861|4493966|152787|152786|81...,100|69|77|85|63|87|68|98|64|99|67|74|61|50|43|...
15932403,XW75HD7O1OY8,78d109891ce82,1541527337,36,interaction item deals,4076774,GR,"Krakow, Poland",desktop,NaN,NaN,NaN
15932423,Y0NMJ7FLTSYT,0b56b5540121c,1541507927,1,search for poi,Castillo de Xátiva,UK,"Játiva, Spain",desktop,NaN,NaN,NaN
15932548,YA0B26091H3Q,fa252ef7d1032,1541489183,46,interaction item info,2326002,AE,"Dubai, United Arab Emirates",mobile,NaN,NaN,NaN
15932569,YH5BH5INZMHX,068dcaa3b08b4,1541518492,1,clickout item,1160332,UK,"London, United Kingdom",desktop,NaN,12669|1160332|47617|6255610|46875|47412|116036...,51|314|147|143|280|102|701|229|81|62|759|120|6...
15932570,YH5BH5INZMHX,068dcaa3b08b4,1541518648,2,search for item,1160332,UK,"London, United Kingdom",desktop,NaN,NaN,NaN
15932607,YQCVP517L5I3,3d5cf2957a6da,1541529174,1,interaction item rating,4834976,ES,"Formentera, Spain",desktop,NaN,NaN,NaN
15932610,YQCVP517L5I3,3d5cf2957a6da,1541529240,4,interaction item rating,1265311,ES,"Formentera, Spain",desktop,NaN,NaN,NaN
15932612,YQCVP517L5I3,3d5cf2957a6da,1541529363,6,interaction item deals,4834976,ES,"Formentera, Spain",desktop,NaN,NaN,NaN
15932650,YQCVP517L5I3,3d5cf2957a6da,1541529448,44,interaction item image,1265311,ES,"Formentera, Spain",desktop,NaN,NaN,NaN
15932661,YQCVP517L5I3,3d5cf2957a6da,1541529478,55,clickout item,5443562,ES,"Formentera, Spain",desktop,NaN,1265311|4834976|5443562|38940|4821722|3971550|...,46|79|45|83|74|64|57|79|414|414
15932683,YRVVFF4XMK2Z,f3814f0165e9c,1541511201,1,search for poi,Arenella beach,UK,"Syracuse, Italy",desktop,NaN,NaN,NaN
15932720,Z6W0KZ1LCB8H,a4c049a08e980,1541497380,2,interaction item image,10218812,AU,"Murray Bridge, Australia",mobile,NaN,NaN,NaN
15932722,Z6W0KZ1LCB8H,a4c049a08e980,1541497387,4,clickout item,10218812,AU,"Murray Bridge, Australia",mobile,NaN,1398634|10907042|10218812|10276592|10160808|10...,249|459|93|201|554|477|71
15932723,Z6W0KZ1LCB8H,a4c049a08e980,1541497390,5,interaction item info,10218812,AU,"Murray Bridge, Australia",mobile,NaN,NaN,NaN
15932724,Z6W0KZ1LCB8H,a4c049a08e980,1541497390,6,interaction item deals,10218812,AU,"Murray Bridge, Australia",mobile,NaN,NaN,NaN
15932729,Z6W0KZ1LCB8H,a4c049a08e980,1541497818,11,interaction item deals,1627067,AU,"Adelaide, Australia",mobile,NaN,NaN,NaN
15932746,Z6W0KZ1LCB8H,a4c049a08e980,1541498612,28,interaction item image,4201464,AU,"Adelaide, Australia",mobile,NaN,NaN,NaN
15932749,Z6W0KZ1LCB8H,a4c049a08e980,1541498622,31,interaction item info,4201464,AU,"Adelaide, Australia",mobile,NaN,NaN,NaN
15932806,ZDPW9IS37UBJ,8b6e093507d36,1541480587,3,clickout item,2627868,IN,"Port Blair, India",desktop,NaN,3045966|2627868|1029890|5464176|1052052|434922...,61|20|57|26|61|17|90|18|62|31|61|53|10|39|86|3...
15932811,ZE8M21HENJ91,f0cceac1f5925,1541516869,1,clickout item,1771251,PL,"Radziejowice, Poland",mobile,NaN,2199498|2258162|1826617|1771183|1771251|131913...,25|60|97|58|37|42|35|31|42|32|37|38|49|60|42|3...

In [4]:
imp = pd.DataFrame(session_t.impressions)
imp = imp[~imp["impressions"].isnull()]
imp = imp.impressions
imp_sp =imp.str.split('|')
imp_sp = imp_sp.apply(lambda x : pd.Series(x))

In [5]:
imp_sin = imp_sp.stack().to_frame('imp_sin')
# imp_sin.T

In [6]:
pri = pd.DataFrame(session_t.prices)
pri = pri[~pri["prices"].isnull()]
pri = pri.prices
pri_sp = pri.str.split('|')
pri_sp = pri_sp.apply(lambda x : pd.Series(x))
# pri_sp

In [7]:
pri_sin = pri_sp.stack().to_frame('pri_sin')
# pri_sin

In [8]:
imp_pri = pd.concat([imp_sin, pri_sin], axis = 1)
# imp_pri

In [9]:
pos = session_t[session_t["action_type"] == "clickout item"]
# pos

In [10]:
pos = pos[["user_id", "step", "action_type", "reference"]]
# pos

In [11]:
pos_last = pos.drop_duplicates(["user_id","action_type"], "last")
# pos_last

In [12]:
pos_ref = pos_last.reference
pos_ref = pos_ref.tolist()
# pos_ref

In [13]:
def pos(data):
    if data in pos_ref:
        return 1
    else:
        return 0

In [ ]:
imp_pri["positive"] = imp_pri['imp_sin'].apply(pos)

In [ ]:
imp_pri

In [ ]:
imp_pri.to_csv(path_or_buf = os.path.abspath('imp_pri.csv'))